import logging
import os
import io
import time
import urllib.request
import tempfile
from datetime import datetime
from pathlib import Path

import pandas as pd
from PIL import Image as PILImage

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.lib.colors import HexColor, white, Color
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Frame,
    Spacer,
    Image,
    Table,
    TableStyle,
    PageBreak,
    Flowable,
)

PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN = 72
CHART_DPI = 150

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

FONT_DIR = Path(__file__).resolve().parent.parent / 'static' / 'fonts'
pdfmetrics.registerFont(TTFont('Fraunces-Medium', str(FONT_DIR / 'Fraunces-Medium.ttf')))
pdfmetrics.registerFont(TTFont('Fraunces-SemiBold', str(FONT_DIR / 'Fraunces-SemiBold.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexSans', str(FONT_DIR / 'IBMPlexSans-Regular.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexSans-Italic', str(FONT_DIR / 'IBMPlexSans-Italic.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexMono', str(FONT_DIR / 'IBMPlexMono-Regular.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexMono-Bold', str(FONT_DIR / 'IBMPlexMono-Bold.ttf')))
pdfmetrics.registerFontFamily('Fraunces', normal='Fraunces-Medium', bold='Fraunces-SemiBold')
pdfmetrics.registerFontFamily('IBMPlexSans', normal='IBMPlexSans', italic='IBMPlexSans-Italic')
pdfmetrics.registerFontFamily('IBMPlexMono', normal='IBMPlexMono', bold='IBMPlexMono-Bold')

from app.core.design_tokens import RED, MINT, GRID_LINE

BRAND_COLOR_DEFAULT = '#D97A34'
CREAM_BG = HexColor('#F7F2E9')
ROW_ALT_COLOR = '#F7F2E9'
ANOMALY_BG_COLOR = '#FEF3C7'
WATERMARK_TEXT = 'Generated by Naxely'

OUTPUT_ROOT = Path('/tmp/naxely')


class _SectionHeader(Flowable):
    def __init__(self, text, brand_color_hex, width=None):
        Flowable.__init__(self)
        self.text = text
        self.brand_color = HexColor(brand_color_hex)
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.height = 36

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        self.canv.setFillColor(self.brand_color)
        self.canv.rect(0, 2, self._width, 28, fill=1, stroke=0)
        self.canv.setFillColor(white)
        self.canv.setFont('Fraunces-SemiBold', 16)
        self.canv.drawString(12, 9, self.text)


class _KPICard(Flowable):
    def __init__(self, name, value_str, trend, trend_pct, brand_color_hex, width=None, highlight=False):
        Flowable.__init__(self)
        self.name = name
        self.value_str = value_str
        self.trend = trend
        self.trend_pct = trend_pct
        self.highlight = highlight
        self.brand_color_hex = brand_color_hex
        self.brand_color = HexColor(brand_color_hex)
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.height = 94 if highlight else 74

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        card_h = 84 if self.highlight else 64
        bg = _brand_tint(self.brand_color_hex) if self.highlight else HexColor('#F9FAFB')
        self.canv.setFillColor(bg)
        self.canv.roundRect(0, 0, self._width, card_h, 6, fill=1, stroke=0)
        self.canv.setFillColor(HexColor('#374151'))
        self.canv.setFont('IBMPlexSans', 9)
        self.canv.drawString(12, card_h - 18, self.name)
        self.canv.setFillColor(self.brand_color)
        val_size = 26 if self.highlight else 22
        self.canv.setFont('IBMPlexMono-Bold', val_size)
        self.canv.drawString(12, card_h - 46 if self.highlight else 18, self.value_str)
        arrow_x = self._width - 12
        arrow_y = card_h - 40 if self.highlight else 24
        s = 7
        if self.trend_pct >= 0:
            color = HexColor(MINT)
            p = self.canv.beginPath()
            p.moveTo(arrow_x - s, arrow_y - s)
            p.lineTo(arrow_x + s, arrow_y - s)
            p.lineTo(arrow_x, arrow_y + s)
            p.close()
        else:
            color = HexColor(RED)
            p = self.canv.beginPath()
            p.moveTo(arrow_x - s, arrow_y + s)
            p.lineTo(arrow_x + s, arrow_y + s)
            p.lineTo(arrow_x, arrow_y - s)
            p.close()
        self.canv.setFillColor(color)
        self.canv.drawPath(p, fill=1, stroke=0)
        self.canv.setFillColor(HexColor('#6B7280'))
        self.canv.setFont('IBMPlexMono', 7.5)
        pct_label = f'recent: {self.trend_pct:+.1f}%'
        self.canv.drawRightString(self._width - 12, 6, pct_label)


class _InsightCard(Flowable):
    def __init__(self, insight, width=None):
        Flowable.__init__(self)
        self.insight = insight
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        sentiment = insight.get('sentiment', 'neutral')
        if sentiment == 'positive':
            self.border_color = HexColor(MINT)
        elif sentiment == 'negative':
            self.border_color = HexColor(RED)
        else:
            self.border_color = HexColor('#6B7280')
        self._build_paragraphs()

    def _build_paragraphs(self):
        text_width = self._width - 5 - 32
        title_style = ParagraphStyle('InsightTitle', fontName='Fraunces-SemiBold', fontSize=11, textColor=HexColor('#111827'), leading=15, wordWrap='LTR')
        mono_style = ParagraphStyle('InsightMono', fontName='IBMPlexMono-Bold', fontSize=9.5, textColor=HexColor('#374151'), leading=14, wordWrap='LTR')
        body_style = ParagraphStyle('InsightBody', fontName='IBMPlexSans', fontSize=9.5, textColor=HexColor('#374151'), leading=14, wordWrap='LTR')
        italic_style = ParagraphStyle('InsightItalic', fontName='IBMPlexSans-Italic', fontSize=9.5, textColor=HexColor('#374151'), leading=14, wordWrap='LTR')

        self.kpi_para = Paragraph(str(self.insight.get('kpi', '')), title_style)
        self.number_para = Paragraph('\U0001F4CA ' + self.insight.get('number', ''), mono_style)
        self.reason_para = Paragraph('\u25B6 ' + self.insight.get('reason', ''), body_style)
        self.action_para = Paragraph('\u2713 ' + self.insight.get('action', ''), italic_style)

        self.kpi_h = self.kpi_para.wrap(text_width, self._width)[1]
        self.number_h = self.number_para.wrap(text_width, self._width)[1]
        self.reason_h = self.reason_para.wrap(text_width, self._width)[1]
        self.action_h = self.action_para.wrap(text_width, self._width)[1]
        self.height = int(self.kpi_h + 8 + self.number_h + 6 + self.reason_h + 6 + self.action_h + 16)

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        self.canv.setFillColor(self.border_color)
        self.canv.rect(0, 0, 5, self.height, fill=1, stroke=0)
        self.canv.setFillColor(white)
        self.canv.rect(5, 0, self._width - 5, self.height, fill=1, stroke=0)
        self.canv.setStrokeColor(HexColor('#E5E7EB'))
        self.canv.rect(5, 0, self._width - 5, self.height, fill=0, stroke=1)

        x = 16
        text_width = self._width - 5 - 32
        y = self.height - 16

        f = Frame(x, y - self.kpi_h, text_width, self.kpi_h, showBoundary=0)
        f.addFromList([self.kpi_para], self.canv)
        y -= self.kpi_h + 8

        f = Frame(x, y - self.number_h, text_width, self.number_h, showBoundary=0)
        f.addFromList([self.number_para], self.canv)
        y -= self.number_h + 6

        f = Frame(x, y - self.reason_h, text_width, self.reason_h, showBoundary=0)
        f.addFromList([self.reason_para], self.canv)
        y -= self.reason_h + 6

        f = Frame(x, y - self.action_h, text_width, self.action_h, showBoundary=0)
        f.addFromList([self.action_para], self.canv)


class _AnomalyBox(Flowable):
    def __init__(self, message, width=None):
        Flowable.__init__(self)
        self.message = message
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.height = 30

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        self.canv.setFillColor(HexColor(ANOMALY_BG_COLOR))
        self.canv.roundRect(0, 0, self._width, 22, 4, fill=1, stroke=0)
        self.canv.setFillColor(HexColor('#92400E'))
        self.canv.setFont('IBMPlexSans', 9.5)
        display = '\u26A0\uFE0F ' + self.message[:120]
        self.canv.drawString(10, 6, display)


class _CoverBand(Flowable):
    def __init__(self, title, company_name, logo_path, brand_color_hex):
        Flowable.__init__(self)
        self.title = title
        self.company_name = company_name
        self.logo_path = logo_path
        self.brand_color = HexColor(brand_color_hex)
        self.band_height = int(PAGE_HEIGHT * 0.28)
        self.width = PAGE_WIDTH
        self.height = self.band_height

    def wrap(self, availWidth, availHeight):
        return (self.width, self.height)

    def draw(self):
        self.canv.saveState()
        self.canv.translate(-MARGIN, 0)
        self.canv.setFillColor(self.brand_color)
        self.canv.rect(0, 0, self.width, self.band_height, fill=1, stroke=0)
        cx = PAGE_WIDTH / 2

        # --- 1. Logo badge (top-left: 20px from left, 20px from top of band) ---
        logo_bottom_y = self.band_height - 20
        if self.logo_path:
            try:
                img_reader = ImageReader(self.logo_path)
                iw, ih = img_reader.getSize()
                max_draw_h = 56  # badge height including padding
                scale = min(1.0, max_draw_h / ih)
                draw_w = int(iw * scale)
                draw_h = int(ih * scale)

                logo_x = 20
                logo_y = self.band_height - 20 - draw_h

                self.canv.drawImage(
                    img_reader,
                    logo_x,
                    logo_y,
                    width=draw_w,
                    height=draw_h,
                    mask='auto',
                    preserveAspectRatio=True,
                )
                logo_bottom_y = logo_y
            except Exception as e:
                logging.warning(f"[pdf_service] drawImage failed: {e}")

        # --- 2. Company name + Report title (centered in full band) ---
        # Center vertically in the full band, not just space below logo

        COMPANY_FONT = 'Fraunces-SemiBold'
        COMPANY_FONT_SIZE = 28
        TITLE_FONT = 'IBMPlexSans'
        TITLE_FONT_SIZE = 14

        band_center_y = self.band_height * 0.42

        # Company name: centered, vertically centered in full band
        company_y = band_center_y + COMPANY_FONT_SIZE * 0.3
        self.canv.setFillColor(white)
        self.canv.setFont(COMPANY_FONT, COMPANY_FONT_SIZE)
        if self.company_name:
            self.canv.drawCentredString(cx, company_y, self.company_name)

        # Report title: 8px below band center baseline
        title_y = band_center_y - COMPANY_FONT_SIZE - 8
        self.canv.setFillColor(white)
        self.canv.setFont(TITLE_FONT, TITLE_FONT_SIZE)
        self.canv.drawCentredString(cx, title_y, self.title)

        self.canv.restoreState()


class _CoverMotif(Flowable):
    """Brand motif (3 ascending bars, common baseline) centred below the cover band."""
    def __init__(self, brand_color_hex):
        Flowable.__init__(self)
        self.brand_color = HexColor(brand_color_hex)
        self.content_size = 48  # 48×48 pt content area (uniform 2× favicon viewBox)
        self.width = PAGE_WIDTH
        self.height = self.content_size + 40  # 20pt pad above + below

    def wrap(self, availWidth, availHeight):
        return (self.width, self.height)

    def draw(self):
        self.canv.saveState()
        self.canv.translate(-MARGIN, 0)
        cx = self.width / 2
        area_left = cx - self.content_size / 2
        area_bottom = 20  # 20pt padding from bottom of flowable
        baseline = area_bottom + 4  # 4pt from area bottom = common bar baseline
        self.canv.setFillColor(self.brand_color)
        # Bars at uniform 2× from 24×24 viewBox; common baseline, ascending tops
        self.canv.roundRect(area_left + 4,    baseline, 11, 18,  2.4, fill=1, stroke=0)
        self.canv.roundRect(area_left + 18.5, baseline, 11, 29,  2.4, fill=1, stroke=0)
        self.canv.roundRect(area_left + 33,   baseline, 11, 40,  2.4, fill=1, stroke=0)
        self.canv.restoreState()


class _CoverRule(Flowable):
    """Thin horizontal rule separating hero area from metadata."""
    def __init__(self, grid_color_hex):
        Flowable.__init__(self)
        self.grid_color = HexColor(grid_color_hex)
        self._width = PAGE_WIDTH - 2 * MARGIN
        self.height = 20  # spacing only; the rule is vertically centred

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        self.canv.saveState()
        self.canv.setStrokeColor(self.grid_color)
        self.canv.setLineWidth(0.5)
        self.canv.line(0, self.height / 2, self._width, self.height / 2)
        self.canv.restoreState()


def _strip_standard_fonts(pdf_path: str) -> None:
    """Remove unused standard PDF fonts from page Resources and their Tf
    operators from content streams, so the font listing is clean.

    ReportLab always registers the 14 standard PDF fonts on every canvas and
    writes a Tf operator for Helvetica 12pt as the initial graphics state.
    Since no text is ever rendered with these fonts, both the resource entry
    and the Tf call can be safely removed.
    """
    try:
        import pikepdf
        from pikepdf import parse_content_stream, unparse_content_stream, Operator
    except ImportError:
        return
    try:
        pdf = pikepdf.open(pdf_path)

        std = {'/Helvetica', '/Helvetica-Bold', '/Helvetica-Oblique', '/Helvetica-BoldOblique',
               '/Times-Roman', '/Times-Bold', '/Times-Italic', '/Times-BoldItalic',
               '/Courier', '/Courier-Bold', '/Courier-Oblique', '/Courier-BoldOblique',
               '/Symbol', '/ZapfDingbats'}

        # Pass 1: collect standard-font resource keys per page (before any
        # modifications, since /Font dicts may be shared via indirect refs).
        page_std_keys = []
        for page in pdf.pages:
            fonts = page.get('/Resources', {}).get('/Font', pikepdf.Dictionary())
            keys = set()
            for key in fonts:
                try:
                    if str(fonts[key].get('/BaseFont')) in std:
                        keys.add(str(key))
                except Exception:
                    pass
            page_std_keys.append(keys)

        # Pass 2: remove from Resources and content streams
        for page, std_keys in zip(pdf.pages, page_std_keys):
            if not std_keys:
                continue

            # Remove from /Font
            fonts = page.get('/Resources', {}).get('/Font', pikepdf.Dictionary())
            for key in list(fonts.keys()):
                if str(key) in std_keys:
                    del fonts[key]

            # Remove Tf operators from content stream
            cs = page.get('/Contents')
            if cs is not None:
                ops = parse_content_stream(cs)
                filtered = [(o, op) for o, op in ops
                            if not (op == Operator('Tf') and str(list(o)[0]) in std_keys)]
                cs.write(unparse_content_stream(filtered))

        import tempfile, shutil
        tmp = tempfile.mktemp(suffix='.pdf')
        pdf.save(tmp)
        pdf.close()
        shutil.move(tmp, pdf_path)
    except Exception as e:
        import traceback
        traceback.print_exc()


def _brand_tint(brand_hex, alpha=0.08):
    c = HexColor(brand_hex)
    r = c.red * alpha + 1.0 * (1.0 - alpha)
    g = c.green * alpha + 1.0 * (1.0 - alpha)
    b = c.blue * alpha + 1.0 * (1.0 - alpha)
    return Color(r, g, b)


class _RecommendationCard(Flowable):
    def __init__(self, index, text, brand_color_hex, width=None):
        Flowable.__init__(self)
        self.index = index
        self.text = text
        self.brand_color_hex = brand_color_hex
        self.brand_color = HexColor(brand_color_hex)
        self._full_width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.badge_size = 28
        self.badge_x = 12
        self.text_x = self.badge_x + self.badge_size + 12
        self.text_width = self._full_width - self.text_x - 12
        self.rec_style = ParagraphStyle(
            'RecCardText', fontName='IBMPlexSans', fontSize=10,
            textColor=HexColor('#374151'), leading=14,
            spaceBefore=0, spaceAfter=0,
        )
        self.para = Paragraph(text, self.rec_style)

    def wrap(self, availWidth, availHeight):
        _, ph = self.para.wrap(self.text_width, min(availHeight, 200))
        self._para_height = ph
        self.height = max(50, ph + 24)
        return (self._full_width, self.height)

    def draw(self):
        tint = _brand_tint(self.brand_color_hex)
        self.canv.setFillColor(tint)
        self.canv.roundRect(0, 0, self._full_width, self.height, 6, fill=1, stroke=0)
        bs, bx = self.badge_size, self.badge_x
        by = (self.height - bs) / 2
        self.canv.setFillColor(self.brand_color)
        self.canv.roundRect(bx, by, bs, bs, 14, fill=1, stroke=0)
        self.canv.setFillColor(white)
        self.canv.setFont('Fraunces-SemiBold', 12)
        self.canv.drawCentredString(bx + bs / 2, by + 7, str(self.index))
        para_y = (self.height - self._para_height) / 2
        self.para.drawOn(self.canv, self.text_x, para_y)


def _hex_to_reportlab(hex_str: str) -> HexColor:
    return HexColor(hex_str)


def _download_logo(logo_url: str) -> str | None:
    t0 = time.time()
    logging.info("[pdf_service] logo download start")
    try:
        req = urllib.request.Request(logo_url, headers={'User-Agent': 'Naxely/1.0'})
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = resp.read()
        elapsed = round(time.time() - t0, 2)
        logging.info(f"[pdf_service] logo download done: {elapsed:.2f}s")

        img = PILImage.open(io.BytesIO(data)).convert('RGBA')

        # Resize logo to max height 36px (fits cleanly in cover band)
        max_h = 36
        if img.height > max_h:
            ratio = max_h / img.height
            img = img.resize((int(img.width * ratio), max_h), PILImage.Resampling.LANCZOS)

        # Add padding around the logo
        pad_x, pad_y = 12, 8
        badge_w = img.width + pad_x * 2
        badge_h = img.height + pad_y * 2

        # Create white background with rounded corners using PIL
        from PIL import ImageDraw
        badge = PILImage.new('RGBA', (badge_w, badge_h), (0, 0, 0, 0))
        draw = ImageDraw.Draw(badge)
        draw.rounded_rectangle(
            [(0, 0), (badge_w - 1, badge_h - 1)],
            radius=6,
            fill=(255, 255, 255, 255)
        )
        # Paste logo centered on badge
        badge.paste(img, (pad_x, pad_y), mask=img.split()[3])

        # Save as RGBA PNG with transparent corners (badge on transparent canvas)
        tmp = tempfile.NamedTemporaryFile(suffix='.png', delete=False)
        tmp_path = tmp.name
        tmp.close()
        badge.save(tmp_path, 'PNG')

        logging.info(f"[pdf_service] _download_logo success: {tmp_path}")
        return tmp_path
    except Exception as e:
        logging.warning(f"[pdf_service] _download_logo failed: {e}")
        return None


def _format_number(val) -> str:
    if isinstance(val, float):
        if abs(val) >= 1_000_000:
            return f'{val/1_000_000:.1f}M'
        if abs(val) >= 1_000:
            return f'{val/1_000:.1f}K'
        if val == int(val):
            return str(int(val))
        return f'{val:.2f}'
    return str(val)


def _add_watermark(canvas, doc):
    canvas.saveState()
    canvas.setFont('Fraunces-Medium', 50)
    canvas.setFillColor(Color(0, 0, 0, alpha=0.06))
    canvas.translate(PAGE_WIDTH / 2, PAGE_HEIGHT / 2)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, WATERMARK_TEXT)
    canvas.restoreState()


def _on_page(canvas, doc, add_watermark=False, is_white_label=False, company_name=''):
    canvas.saveState()
    canvas.setFillColor(CREAM_BG)
    canvas.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)
    canvas.setFont('IBMPlexSans', 8)
    canvas.setFillColor(HexColor('#9CA3AF'))
    if is_white_label:
        if company_name:
            footer_text = f'{company_name} — {datetime.now().strftime("%B %d, %Y")}'
            canvas.drawString(MARGIN, 30, footer_text)
    else:
        canvas.drawString(MARGIN, 30, f'Naxely Report — {datetime.now().strftime("%B %d, %Y")}')
    canvas.drawRightString(PAGE_WIDTH - MARGIN, 30, f'Page {doc.page}')
    if add_watermark:
        _add_watermark(canvas, doc)
    canvas.restoreState()


def _compute_kpi_data(df: pd.DataFrame, config: dict, ai_content: dict, brand_color_hex: str) -> list[dict]:
    if config.get("_precomputed_kpis"):
        return config["_precomputed_kpis"]

    metric_cols = config.get('metric_columns', [])
    if not metric_cols:
        metric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    metric_cols = metric_cols[:5]

    from app.services.data_service import _compute_trend, _compute_trend_percentage, _try_clean_numeric

    kpis = []
    for col in metric_cols:
        if col not in df.columns:
            continue
        series = _try_clean_numeric(df[col]).dropna()
        if len(series) == 0:
            continue
        total = series.sum()
        trend = _compute_trend(series)
        trend_pct = _compute_trend_percentage(series)
        kpis.append({
            'name': 'Total ' + col.replace('_', ' ').title(),
            'value': _format_number(total),
            'trend': trend,
            'trend_pct': trend_pct,
        })
    return kpis[:5]


def build_sync(
    df: pd.DataFrame,
    chart_paths: list[str],
    ai_content: dict,
    config: dict,
    user_data: dict,
) -> str:
    report_id = config.get('report_id', 'unknown')
    logging.info(f"[pdf_service] build_sync started — report_id={report_id}")
    brand_color = user_data.get('brand_color', BRAND_COLOR_DEFAULT)
    content_width = PAGE_WIDTH - 2 * MARGIN

    is_free = user_data.get('tier', 'free') == 'free'
    is_white_label = user_data.get('tier') == 'agency'
    company_name = user_data.get('company_name', '')

    output_dir = OUTPUT_ROOT / str(report_id)
    output_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = str(output_dir / 'report.pdf')

    def on_page(canvas, doc):
        _on_page(canvas, doc, add_watermark=is_free, is_white_label=is_white_label, company_name=company_name)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
    )

    body_style = ParagraphStyle(
        'BodyText2',
        fontName='IBMPlexSans',
        fontSize=10,
        textColor=HexColor('#374151'),
        alignment=TA_JUSTIFY,
        spaceAfter=8,
        leading=14,
    )

    toc_h1_style = ParagraphStyle(
        'TOCH1',
        fontName='IBMPlexSans',
        fontSize=11,
        textColor=HexColor('#374151'),
        leftIndent=20,
        spaceBefore=4,
        spaceAfter=2,
        leading=14,
    )

    story = []
    body_story: list = []
    toc_entries = [('Cover Page', '1'), ('Table of Contents', '2')]
    toc_page = 3

    # ────────────────────────────────────────────────────────────
    # SECTION 1 — Cover Page (into main story)
    # ────────────────────────────────────────────────────────────
    logo_path = None
    logo_signed_url = user_data.get('logo_url')
    if logo_signed_url:
        logo_path = _download_logo(logo_signed_url)

    title = config.get('title', 'Marketing Performance Report')
    company_name = user_data.get('company_name', '')

    story.append(_CoverBand(
        title=title, company_name=company_name,
        logo_path=logo_path, brand_color_hex=brand_color,
    ))
    story.append(_CoverMotif(brand_color))

    kpis = _compute_kpi_data(df, config, ai_content, brand_color)
    hero = max(kpis, key=lambda k: abs(k.get('trend_pct', 0))) if kpis else None

    if hero:
        trend_pct = hero['trend_pct']
        if trend_pct > 0:
            arrow_color_hex = MINT
        elif trend_pct < 0:
            arrow_color_hex = RED
        else:
            arrow_color_hex = '#6B7280'
        sign = '+' if trend_pct > 0 else ''
        class _CoverHeroStat(Flowable):
            def __init__(self, hero, sign, trend_pct, arrow_color_hex, brand_color):
                Flowable.__init__(self)
                self.hero = hero
                self.sign = sign
                self.trend_pct = trend_pct
                self.arrow_color = HexColor(arrow_color_hex)
                self.brand_color = HexColor(brand_color)
                self._width = content_width
                self.height = 56

            def wrap(self, availWidth, availHeight):
                return (self._width, self.height)

            def draw(self):
                cx = self._width / 2
                label = f'{self.hero["name"]}: {self.sign}{self.trend_pct:.1f}%'
                self.canv.setFillColor(self.brand_color)
                self.canv.setFont('Fraunces-SemiBold', 22)
                self.canv.drawCentredString(cx, 18, label)
                s = 9
                arrow_x = cx + self.canv.stringWidth(label, 'Fraunces-SemiBold', 22) / 2 + 16
                arrow_y = 28
                if self.trend_pct > 0:
                    p = self.canv.beginPath()
                    p.moveTo(arrow_x - s, arrow_y - s)
                    p.lineTo(arrow_x + s, arrow_y - s)
                    p.lineTo(arrow_x, arrow_y + s)
                    p.close()
                elif self.trend_pct < 0:
                    p = self.canv.beginPath()
                    p.moveTo(arrow_x - s, arrow_y + s)
                    p.lineTo(arrow_x + s, arrow_y + s)
                    p.lineTo(arrow_x, arrow_y - s)
                    p.close()
                else:
                    p = self.canv.beginPath()
                    p.moveTo(arrow_x - s, arrow_y - s)
                    p.lineTo(arrow_x - s, arrow_y + s)
                    p.lineTo(arrow_x + s, arrow_y)
                    p.close()
                self.canv.setFillColor(self.arrow_color)
                self.canv.drawPath(p, fill=1, stroke=0)
        story.append(_CoverHeroStat(hero, sign, trend_pct, arrow_color_hex, brand_color))

    story.append(_CoverRule(GRID_LINE))

    info_style = ParagraphStyle(
        'CoverInfo', fontName='IBMPlexSans',
        fontSize=10, textColor=HexColor('#6B7280'),
        alignment=TA_CENTER, spaceAfter=4,
    )
    date_from = config.get('date_from', 'N/A')
    date_to = config.get('date_to', 'N/A')
    if date_from and date_to and date_from != 'N/A':
        story.append(Paragraph(f'From {date_from} to {date_to}', info_style))
    prepared_by = (config.get('brand') or {}).get('prepared_by', '')
    if prepared_by:
        story.append(Paragraph(f'Prepared by: {prepared_by}', info_style))
    story.append(Paragraph(
        f'Prepared on: {datetime.now().strftime("%B %d, %Y")}', info_style,
    ))
    story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 2 — Executive Summary
    # ────────────────────────────────────────────────────────────
    if 'executive_summary' in config.get('sections', []) and ai_content.get('summary'):
        toc_entries.append(('Executive Summary', str(toc_page)))
        toc_page += 1
        body_story.append(_SectionHeader('Executive Summary', brand_color, content_width))
        body_story.append(Spacer(1, 10))
        body_story.append(Paragraph(ai_content['summary'], body_style))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 3 — Key Metrics Overview
    # ────────────────────────────────────────────────────────────
    toc_entries.append(('Key Metrics Overview', str(toc_page)))
    toc_page += 1
    body_story.append(_SectionHeader('Key Metrics Overview', brand_color, content_width))
    body_story.append(Spacer(1, 10))

    for kpi in kpis:
        is_hero = hero is not None and kpi['name'] == hero['name']
        card = _KPICard(
            name=kpi['name'],
            value_str=kpi['value'],
            trend=kpi['trend'],
            trend_pct=kpi.get('trend_pct', 0),
            brand_color_hex=brand_color,
            width=content_width,
            highlight=is_hero,
        )
        body_story.append(card)
        body_story.append(Spacer(1, 8))
    body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 4 — Charts
    # ────────────────────────────────────────────────────────────
    toc_entries.append(('Charts & Visualizations', str(toc_page)))
    toc_page += 1
    body_story.append(_SectionHeader('Charts & Visualizations', brand_color, content_width))
    body_story.append(Spacer(1, 10))

    for i, chart_item in enumerate(chart_paths):
        if isinstance(chart_item, tuple):
            chart_path = chart_item[0]
        else:
            chart_path = chart_item
        if not os.path.isfile(chart_path):
            continue
        try:
            draw_w = content_width
            draw_h = 220
            chart_img = Image(chart_path, width=draw_w, height=draw_h)
            chart_img.hAlign = 'CENTER'
            body_story.append(chart_img)
            body_story.append(Spacer(1, 16))
            if i < len(chart_paths) - 1:
                body_story.append(PageBreak())
        except Exception:
            continue
    body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 5 — AI Insight Cards
    # ────────────────────────────────────────────────────────────
    insights = ai_content.get('insights') or []
    ai_skipped = config.get('_ai_skipped', False)
    if 'insights' in config.get('sections', []):
        toc_entries.append(('AI Insights', str(toc_page)))
        toc_page += 1
        body_story.append(_SectionHeader('AI Insights', brand_color, content_width))
        body_story.append(Spacer(1, 10))
        if ai_skipped:
            body_story.append(Paragraph(
                "⚠️ AI insights were rate-limited during generation. Regenerate this report to include them.",
                body_style,
            ))
        elif insights:
            for ins in insights[:5]:
                card = _InsightCard(ins, width=content_width)
                body_story.append(card)
                body_story.append(Spacer(1, 8))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 6 — Anomaly Flags
    # ────────────────────────────────────────────────────────────
    anomalies = ai_content.get('anomalies') or []
    if anomalies:
        toc_entries.append(('Anomaly Flags', str(toc_page)))
        toc_page += 1
        body_story.append(_SectionHeader('Anomaly Flags', brand_color, content_width))
        body_story.append(Spacer(1, 10))
        for anomaly in anomalies[:10]:
            msg = anomaly.get('message', 'Anomaly detected')
            box = _AnomalyBox(msg, width=content_width)
            body_story.append(box)
            body_story.append(Spacer(1, 6))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 7 — Data Table
    # ────────────────────────────────────────────────────────────
    toc_entries.append(('Data Table', str(toc_page)))
    toc_page += 1
    body_story.append(_SectionHeader('Data Table', brand_color, content_width))
    body_story.append(Spacer(1, 10))

    display_df = df.copy()
    if len(display_df) > 50:
        display_df = display_df.head(50)

    table_data = []
    header_row = [str(c) for c in display_df.columns]
    table_data.append(header_row)
    for _, row in display_df.iterrows():
        table_data.append([str(v) if pd.notna(v) else '' for v in row])

    col_count = len(header_row)
    col_width = min(content_width / max(col_count, 1), 120)
    col_widths = [col_width] * col_count

    data_table = Table(table_data, colWidths=col_widths, repeatRows=1)

    table_style_commands = [
        ('BACKGROUND', (0, 0), (-1, 0), HexColor(brand_color)),
        ('TEXTCOLOR', (0, 0), (-1, 0), white),
        ('FONTNAME', (0, 0), (-1, 0), 'Fraunces-SemiBold'),
        ('FONTSIZE', (0, 0), (-1, 0), 8),
        ('FONTNAME', (0, 1), (-1, -1), 'IBMPlexMono'),
        ('FONTSIZE', (0, 1), (-1, -1), 7),
        ('GRID', (0, 0), (-1, -1), 0.5, HexColor(GRID_LINE)),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]

    for row_idx in range(1, len(table_data)):
        if row_idx % 2 == 0:
            table_style_commands.append(
                ('BACKGROUND', (0, row_idx), (-1, row_idx), HexColor(ROW_ALT_COLOR))
            )

    data_table.setStyle(TableStyle(table_style_commands))
    body_story.append(data_table)
    body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 8 — Recommendations
    # ────────────────────────────────────────────────────────────
    toc_entries.append(('Recommendations', str(toc_page)))
    toc_page += 1
    body_story.append(_SectionHeader('Recommendations', brand_color, content_width))
    body_story.append(Spacer(1, 10))

    if ai_skipped:
        body_story.append(Paragraph(
            "⚠️ Recommendations were rate-limited during generation. Regenerate this report to include them.",
            body_style,
        ))
    else:
        all_insights = ai_content.get('insights') or []
        actions = [ins.get('action', '') for ins in all_insights if ins.get('action')]

        if actions:
            for idx, action in enumerate(actions, 1):
                body_story.append(_RecommendationCard(idx, action, brand_color, content_width))
                body_story.append(Spacer(1, 8))
        else:
            body_story.append(Paragraph('No recommendations available.', body_style))
    body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 9 — Appendix
    # ────────────────────────────────────────────────────────────
    if 'appendix' in config.get('sections', []):
        toc_entries.append(('Appendix — Raw Data', str(toc_page)))
        toc_page += 1
        body_story.append(_SectionHeader('Appendix — Raw Data', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        appendix_df = df.copy()
        if len(appendix_df) > 100:
            appendix_df = appendix_df.head(100)

        app_table_data = []
        app_header = [str(c) for c in appendix_df.columns]
        app_table_data.append(app_header)
        for _, row in appendix_df.iterrows():
            app_table_data.append([str(v) if pd.notna(v) else '' for v in row])

        app_col_count = len(app_header)
        app_col_width = min(content_width / max(app_col_count, 1), 120)
        app_col_widths = [app_col_width] * app_col_count

        app_table = Table(app_table_data, colWidths=app_col_widths, repeatRows=1)

        app_style_commands = [
            ('BACKGROUND', (0, 0), (-1, 0), HexColor(brand_color)),
            ('TEXTCOLOR', (0, 0), (-1, 0), white),
            ('FONTNAME', (0, 0), (-1, 0), 'Fraunces-SemiBold'),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('FONTNAME', (0, 1), (-1, -1), 'IBMPlexMono'),
            ('FONTSIZE', (0, 1), (-1, -1), 7),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor(GRID_LINE)),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]
        for row_idx in range(1, len(app_table_data)):
            if row_idx % 2 == 0:
                app_style_commands.append(
                    ('BACKGROUND', (0, row_idx), (-1, row_idx), HexColor(ROW_ALT_COLOR))
                )

        app_table.setStyle(TableStyle(app_style_commands))
        body_story.append(app_table)

    # ────────────────────────────────────────────────────────────
    # TOC — built from recorded entries, inserted after cover
    # ────────────────────────────────────────────────────────────
    story.append(_SectionHeader('Table of Contents', brand_color, content_width))
    story.append(Spacer(1, 12))
    for label, pg in toc_entries:
        dots = '.' * max(2, 60 - len(label) - len(pg))
        line = f'{label}  {dots}  {pg}'
        story.append(Paragraph(line, toc_h1_style))
    story.append(PageBreak())

    story.extend(body_story)

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    logging.info(f"[pdf_service] build_sync completed — report_id={report_id}")

    _strip_standard_fonts(pdf_path)

    if logo_path:
        try:
            os.unlink(logo_path)
        except OSError:
            pass

    return pdf_path
