import logging
import os
import io

import subprocess
import sys
import time
import urllib.request
import tempfile
from datetime import datetime
from pathlib import Path

import pandas as pd
from PIL import Image as PILImage

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.lib.colors import HexColor, white, Color
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Frame,
    Spacer,
    Image,
    Table,
    TableStyle,
    PageBreak,
    Flowable,
)

PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN = 72
CHART_DPI = 150

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

FONT_DIR = Path(__file__).resolve().parent.parent / 'static' / 'fonts'
pdfmetrics.registerFont(TTFont('Fraunces-Medium', str(FONT_DIR / 'Fraunces-Medium.ttf')))
pdfmetrics.registerFont(TTFont('Fraunces-SemiBold', str(FONT_DIR / 'Fraunces-SemiBold.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexSans', str(FONT_DIR / 'IBMPlexSans-Regular.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexSans-Italic', str(FONT_DIR / 'IBMPlexSans-Italic.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexSans-Bold', str(FONT_DIR / 'IBMPlexSans-Bold.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexMono', str(FONT_DIR / 'IBMPlexMono-Regular.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexMono-Bold', str(FONT_DIR / 'IBMPlexMono-Bold.ttf')))
pdfmetrics.registerFontFamily('Fraunces', normal='Fraunces-Medium', bold='Fraunces-SemiBold')
pdfmetrics.registerFontFamily('IBMPlexSans', normal='IBMPlexSans', italic='IBMPlexSans-Italic')
pdfmetrics.registerFontFamily('IBMPlexMono', normal='IBMPlexMono', bold='IBMPlexMono-Bold')

from app.core.design_tokens import GRID_LINE

# ── Ledger design tokens ────────────────────────────────────────────────
INK = '#1A1D24'
PAPER_BG = '#FAFAF7'
RULE = '#D8D6CE'
RULE_STRONG = '#1A1D24'
MUTED = '#6B6E76'
RUST = '#A8481F'
DELTA_UP = '#5B7C55'   # muted ledger green for positive deltas (matches _InsightCard)

BRAND_COLOR_DEFAULT = '#D97A34'
ROW_ALT_COLOR = '#F2F1EB'
WATERMARK_TEXT = 'Generated by Naxely'

OUTPUT_ROOT = Path('/tmp/naxely')


class _SectionHeader(Flowable):
    def __init__(self, text, brand_color_hex, width=None):
        Flowable.__init__(self)
        self.text = text
        self.brand_color = HexColor(brand_color_hex)
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.height = 40

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        # Ledger section header: plain serif heading + hairline rule, no colored band.
        self.canv.setFillColor(HexColor(INK))
        self.canv.setFont('Fraunces-SemiBold', 20)
        self.canv.drawString(0, 22, self.text)
        self.canv.setStrokeColor(HexColor(RULE_STRONG))
        self.canv.setLineWidth(0.75)
        self.canv.line(0, 8, self._width, 8)


class _KPIRow(Flowable):
    """Ledger line-item for a single KPI: serif index, metric name, mono value,
    colored trend — hairline rules above and below the row."""

    def __init__(self, kpi, index, content_width, brand_color_hex):
        Flowable.__init__(self)
        self.kpi = kpi
        self.index = index
        self.brand_color_hex = brand_color_hex
        self._width = content_width
        self.height = 48

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        c = self.canv
        w = self._width
        h = self.height
        c.saveState()

        # hairlines above and below the ledger row
        c.setStrokeColor(HexColor(RULE))
        c.setLineWidth(0.4)
        c.line(0, 0, w, 0)
        c.line(0, h, w, h)

        # index — serif, muted
        c.setFillColor(HexColor(MUTED))
        c.setFont('Fraunces-Medium', 13)
        c.drawString(0, h - 30, str(self.index).zfill(2))

        # name — bold sans
        c.setFillColor(HexColor(INK))
        c.setFont('IBMPlexSans-Bold', 10)
        c.drawString(30, h - 18, str(self.kpi.get('name', '')))

        # value — mono bold, right of centre
        value = str(self.kpi.get('value', ''))
        c.setFillColor(HexColor(INK))
        c.setFont('IBMPlexMono-Bold', 14)
        c.drawRightString(w - 88, (h - 14) / 2 - 2, value)

        # trend — colored, far right. Colorblind-safe: arrow shape + sign +
        # color all carry direction, and up/down use the semantic ledger
        # mint/rust pair consistently with the AI insight cards.
        trend_pct = self.kpi.get('trend_pct', 0) or 0
        trend_color = DELTA_UP if trend_pct >= 0 else RUST
        sign = '+' if trend_pct >= 0 else '-'
        arrow = '\u2191' if trend_pct >= 0 else '\u2193'
        c.setFillColor(HexColor(trend_color))
        c.setFont('IBMPlexSans-Bold', 9)
        c.drawRightString(w, (h - 9) / 2 - 2,
                          f"{arrow} {sign} {abs(trend_pct):.1f}%")

        # qualifier under the trend — labels which calculation produced the
        # % (monthly-aggregate trend vs raw first-to-last), so the card never
        # silently contradicts a chart caption that uses the other measure
        qualifier = _trend_qualifier(self.kpi.get('trend_label', ''))
        if qualifier:
            c.setFillColor(HexColor(MUTED))
            c.setFont('IBMPlexSans-Bold', 6.5)
            c.drawRightString(w, 3, qualifier)

        c.restoreState()


class _KPICard(Flowable):
    """Tinted card for a single KPI — vertical layout, larger value."""

    def __init__(self, kpi, index, width, brand_color_hex):
        Flowable.__init__(self)
        self.kpi = kpi
        self.index = index
        self.width = width
        self.brand_color_hex = brand_color_hex
        self.height = 110

    def wrap(self, availWidth, availHeight):
        return (self.width, self.height)

    def draw(self):
        kpi = self.kpi
        w = self.width
        h = self.height
        c = self.canv
        c.saveState()
        # tinted background
        tint = _brand_tint(self.brand_color_hex, alpha=0.07)
        c.setFillColor(tint)
        c.roundRect(0, 0, w, h, 8, fill=1, stroke=0)
        # hairline border
        c.setStrokeColor(HexColor(RULE))
        c.setLineWidth(0.6)
        c.roundRect(0, 0, w, h, 8, fill=0, stroke=1)
        # index — top left, muted serif
        c.setFillColor(HexColor(MUTED))
        c.setFont('Fraunces-Medium', 10)
        c.drawString(10, h - 18, str(self.index).zfill(2))
        # name — bold sans, centered below index
        name = str(kpi.get('name', '') or '')
        c.setFillColor(HexColor(MUTED))
        c.setFont('IBMPlexSans-Bold', 7.5)
        # keep original case to match PDF text extraction (test expects 'Total Units Sold', not upper)
        avail_name_w = w - 20
        display_name = name
        if c.stringWidth(display_name, 'IBMPlexSans-Bold', 7.5) > avail_name_w:
            display_name = _truncate_words(display_name, 28)
        c.drawCentredString(w/2, h - 30, display_name)
        # value — large mono bold, centered
        value = str(kpi.get('value', '') or '')
        c.setFillColor(HexColor(INK))
        c.setFont('IBMPlexMono-Bold', 26)
        c.drawCentredString(w/2, h/2 + 2, value)
        # trend — colored, centered below value
        trend_pct = kpi.get('trend_pct', 0) or 0
        trend_color = DELTA_UP if trend_pct >= 0 else RUST
        sign = '+' if trend_pct >= 0 else ''
        arrow = '\u2191' if trend_pct >= 0 else '\u2193'
        c.setFillColor(HexColor(trend_color))
        c.setFont('IBMPlexSans-Bold', 9)
        c.drawCentredString(w/2, h/2 - 16, f"{arrow} {sign}{abs(trend_pct):.1f}%")
        qualifier = _trend_qualifier(kpi.get('trend_label', ''))
        if qualifier:
            c.setFillColor(HexColor(MUTED))
            c.setFont('IBMPlexSans-Bold', 6.5)
            c.drawCentredString(w/2, h/2 - 28, qualifier)
        c.restoreState()


def _build_kpi_grid_flowables(kpis: list[dict], brand_color: str, content_width: float) -> list:
    """Shared KPI grid builder — single source for merged and standalone KPI pages.

    Branches: n<=3 single row (n==1 centered at 60% width), n==4 2x2, n==5 3+2 (BOTTOM2 sentinel).
    Fixes n==1 clipping: card width must equal table cell width (single_w), not content_width.
    Returns list of Flowables (Tables + Spacers) ready to append to story.
    """
    n = len(kpis)
    if n == 0:
        return []
    gap = 12
    cards = [(kpi, i) for i, kpi in enumerate(kpis, start=1)]
    rows: list = []
    if n == 1:
        single_w = min(content_width * 0.60, 300)
        rows.append([_KPICard(cards[0][0], cards[0][1], single_w, brand_color)])
    elif n <= 3:
        card_w = (content_width - gap * (n - 1)) / n
        row = [_KPICard(kpi, idx, card_w, brand_color) for kpi, idx in cards]
        rows.append(row)
    elif n == 4:
        card_w = (content_width - gap) / 2
        rows.append([_KPICard(cards[0][0], cards[0][1], card_w, brand_color), _KPICard(cards[1][0], cards[1][1], card_w, brand_color)])
        rows.append([_KPICard(cards[2][0], cards[2][1], card_w, brand_color), _KPICard(cards[3][0], cards[3][1], card_w, brand_color)])
    else:  # n == 5
        card_w3 = (content_width - gap * 2) / 3
        rows.append([_KPICard(cards[0][0], cards[0][1], card_w3, brand_color), _KPICard(cards[1][0], cards[1][1], card_w3, brand_color), _KPICard(cards[2][0], cards[2][1], card_w3, brand_color)])
        rows.append('BOTTOM2')
    # Build flowables
    flowables: list = []
    # Need bottom_cards for n==5 case
    bottom_cards = [cards[3], cards[4]] if n == 5 else []
    for idx, row in enumerate(rows):
        if row == 'BOTTOM2':
            card_w2 = (content_width - gap) / 2
            t = Table([[_KPICard(bottom_cards[0][0], bottom_cards[0][1], card_w2, brand_color), _KPICard(bottom_cards[1][0], bottom_cards[1][1], card_w2, brand_color)]], colWidths=[card_w2, card_w2], hAlign='CENTER', spaceBefore=6, spaceAfter=6)
            t.setStyle(TableStyle([
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 0),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            flowables.append(t)
        else:
            cols = len(row)  # type: ignore
            if cols == 1:
                single_w = min(content_width * 0.60, 300)
                t = Table([[row[0]]], colWidths=[single_w], hAlign='CENTER')  # type: ignore
            elif cols == 2:
                card_w = (content_width - gap) / 2
                t = Table([row], colWidths=[card_w] * 2, hAlign='CENTER')  # type: ignore
            elif cols == 3:
                card_w = (content_width - gap * 2) / 3
                t = Table([row], colWidths=[card_w] * 3, hAlign='CENTER')  # type: ignore
            else:
                t = Table([row], hAlign='CENTER')  # type: ignore
            t.setStyle(TableStyle([
                ('LEFTPADDING', (0, 0), (-1, -1), 6),
                ('RIGHTPADDING', (0, 0), (-1, -1), 6),
                ('TOPPADDING', (0, 0), (-1, -1), 6),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ]))
            flowables.append(t)
        if idx < len(rows) - 1:
            flowables.append(Spacer(1, gap))
    return flowables


class _TOCPageMarker(Flowable):
    """Zero-height marker that records its actual page number during layout.

    Inserted immediately before each section's _SectionHeader. During the
    first layout pass, draw() captures self.canv.getPageNumber() into the
    shared page_map dict. The second pass then builds the TOC with those
    accurate numbers, preserving all existing TOC styling.
    """
    def __init__(self, key: str, page_map: dict):
        Flowable.__init__(self)
        self.key = key
        self.page_map = page_map
        self.width = 0
        self.height = 0

    def wrap(self, availWidth, availHeight):
        return (0, 0)

    def draw(self):
        try:
            self.page_map[self.key] = int(self.canv.getPageNumber())
        except Exception:
            pass


def _wrap_text_lines(text: str, font_name: str, font_size: float, max_width: float) -> list[str]:
    """Greedy word wrap of `text` to `max_width` at the given font. Returns a
    list of lines, each fitting the box; an unbreakable word wider than the box
    is emitted alone rather than dropped."""
    lines, cur = [], ''
    for word in text.split(' '):
        trial = f'{cur} {word}'.strip()
        if cur and pdfmetrics.stringWidth(trial, font_name, font_size) > max_width:
            lines.append(cur)
            cur = word
        else:
            cur = trial
    if cur:
        lines.append(cur)
    return lines


def _fit_text_lines(text: str, font_name: str, font_size: float, max_width: float, max_lines: int) -> list[str]:
    """Wrap `text` to at most `max_lines` lines that fit `max_width`. When the
    text is longer, the final line is truncated at a word boundary with '…'
    rather than cutting mid-word."""
    lines = _wrap_text_lines(text, font_name, font_size, max_width)
    if len(lines) <= max_lines:
        return lines
    head = lines[:max_lines - 1]
    words = ' '.join(lines[max_lines - 1:]).split(' ')
    for n in range(len(words), 0, -1):
        candidate = ' '.join(words[:n]) + '\u2026'
        if pdfmetrics.stringWidth(candidate, font_name, font_size) <= max_width:
            return head + [candidate]
    return head + ['\u2026']


def _trend_qualifier(label: str) -> str:
    """Human-readable qualifier for a KPI trend %. Maps the machine
    `trend_label` ('recent' = monthly-aggregate trend, 'change' = raw
    first-to-last) to the phrase printed under the Key Metrics %."""
    return {
        'recent': 'monthly trend',
        'change': 'first-to-last',
    }.get(label, label)


def _truncate_words(text: str, limit: int) -> str:
    """Truncate `text` to at most `limit` characters at a word boundary,
    appending '…' — the char-based analogue of `_fit_text_lines` used where a
    fixed budget (table cells) applies. A single unbreakable word wider than
    the budget is cut at the limit rather than dropped."""
    if len(text) <= limit:
        return text
    words = text.split(' ')
    for n in range(len(words), 0, -1):
        candidate = ' '.join(words[:n])
        if len(candidate) <= limit - 1:
            return candidate + '\u2026'
    return text[:limit - 1] + '\u2026'


def _sanitize_for_pdf(text: str) -> str:
    """Replace Unicode chars not covered by IBMPlexSans/Fraunces.

    The Groq AI model frequently emits U+2011 (non-breaking hyphen) in
    strings like '6.54-hour', which renders as a box glyph in the PDF
    because the TTF lacks that codepoint. Replace with the nearest
    ASCII equivalent generically, since summary text varies per report.
    """
    if not text:
        return text
    repl = {
        '\u2011': '-',  # non-breaking hyphen — the observed box-glyph culprit
        '\u2010': '-',
        '\u2012': '-',
        '\u2013': '-',  # en dash
        '\u2014': '-',  # em dash
        '\u00a0': ' ',  # NBSP
        '\u2009': ' ',  # thin space
        '\u202f': ' ',  # narrow NBSP
        '\u2000': ' ',
        '\u2001': ' ',
        '\u2002': ' ',
        '\u2003': ' ',
        '\u2004': ' ',
        '\u2005': ' ',
        '\u2006': ' ',
        '\u2007': ' ',
        '\u2008': ' ',
        '\u200a': ' ',
        '\u205f': ' ',
        '\u2018': "'",  # left single quote
        '\u2019': "'",  # right single quote
        '\u201c': '"',  # left double quote
        '\u201d': '"',  # right double quote
    }
    for k, v in repl.items():
        text = text.replace(k, v)
    return text


class _InsightCard(Flowable):
    """Tinted card with severity accent — fixes number clipping, adds background."""

    CARD_H = 84
    LINE_H = 10
    PAD_LEFT = 30
    PAD_TOP = 12
    PAD_RIGHT = 8
    TAG_W = 44
    TAG_H = 13
    TEXT_FONT = 'IBMPlexSans'
    TEXT_SIZE = 8
    NUMBER_FONT = 'IBMPlexMono-Bold'
    NUMBER_SIZE = 13
    MAX_LINES = 2

    _MINT = HexColor(DELTA_UP)
    _RED = HexColor(RUST)
    _AMBER = HexColor('#B45309')
    _INK = HexColor(INK)
    _GRAY = HexColor(MUTED)
    _WHITE = HexColor('#FFFFFF')

    _PRIORITY_COLORS = {
        'high': _RED,
        'medium': _AMBER,
        'low': _MINT,
    }
    _PRIORITY_HEX = {
        'high': RUST,
        'medium': '#B45309',
        'low': DELTA_UP,
    }

    def __init__(self, insight, index=1, width=None):
        Flowable.__init__(self)
        self.insight = insight
        self.index = index
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        self._reason_lines = []
        self._action_lines = []
        self._number_lines = []
        self._layout_text()

    def _layout_text(self):
        ins = self.insight
        number = _sanitize_for_pdf(str(ins.get('number', '') or ''))
        reason = _sanitize_for_pdf(str(ins.get('reason', '') or ''))
        action = _sanitize_for_pdf(str(ins.get('action', '') or ''))
        avail_w = self._width - self.PAD_LEFT - self.PAD_RIGHT
        self._number_lines = _fit_text_lines(number, self.NUMBER_FONT, self.NUMBER_SIZE, avail_w, self.MAX_LINES)
        self._reason_lines = _fit_text_lines(
            reason, self.TEXT_FONT, self.TEXT_SIZE, avail_w, self.MAX_LINES)
        self._action_lines = _fit_text_lines(
            '\u2192 ' + action, self.TEXT_FONT, self.TEXT_SIZE, avail_w, self.MAX_LINES)

    def wrap(self, availWidth, availHeight):
        extra = (len(self._number_lines) - 1) + (len(self._reason_lines) - 1) + (len(self._action_lines) - 1)
        # number lines are taller (13pt vs 8pt) so add extra for number if needed
        if len(self._number_lines) > 1:
            extra += (len(self._number_lines) - 1) * 0.4
        self.width, self.height = self._width, self.CARD_H + extra * self.LINE_H
        return (self.width, self.height)

    def draw(self):
        ins = self.insight
        kpi = _sanitize_for_pdf(str(ins.get('kpi', '') or ''))
        priority = str(ins.get('priority', 'medium')).lower()

        priority_color = self._PRIORITY_COLORS.get(priority, self._AMBER)
        priority_hex = self._PRIORITY_HEX.get(priority, '#B45309')
        w = self._width
        c = self.canv
        h = self.height
        c.saveState()
        # tinted background — alpha 0.12 matching cover hero panel for clear severity tint
        tint = _brand_tint(priority_hex, alpha=0.12)
        c.setFillColor(tint)
        c.roundRect(0, 0, w, h, 6, fill=1, stroke=0)
        # left accent strip — 5pt for clear severity cue
        c.setFillColor(priority_color)
        c.roundRect(0, 0, 5, h, 1.5, fill=1, stroke=0)
        # hairline below the ledger row
        c.setStrokeColor(HexColor(RULE))
        c.setLineWidth(0.4)
        c.line(0, 0, w, 0)

        # index — serif, muted
        c.setFillColor(self._GRAY)
        c.setFont('Fraunces-Medium', 14)
        c.drawString(8, h - 26, str(self.index).zfill(2))

        text_x = self.PAD_LEFT

        # KPI name
        c.setFillColor(self._INK)
        c.setFont('IBMPlexSans-Bold', 9.5)
        c.drawString(text_x, h - self.PAD_TOP - 8, kpi)

        # Severity tag (top right) — keep as is
        tag_x = w - self.TAG_W - self.PAD_RIGHT
        tag_y = h - self.PAD_TOP - 11
        c.setFillColor(priority_color)
        c.roundRect(tag_x, tag_y, self.TAG_W, self.TAG_H, 6.5, fill=1, stroke=0)
        c.setFillColor(self._WHITE)
        c.setFont('IBMPlexSans-Bold', 6.5)
        c.drawCentredString(tag_x + self.TAG_W / 2, tag_y + 3, priority.upper())

        # Number — wrapped, mono bold, larger
        c.setFillColor(self._INK)
        c.setFont(self.NUMBER_FONT, self.NUMBER_SIZE)
        number_y = h - self.PAD_TOP - 26
        for i, line in enumerate(self._number_lines):
            c.drawString(text_x, number_y - i * 14, line)

        # Reason — wrapped, muted
        c.setFillColor(self._GRAY)
        c.setFont(self.TEXT_FONT, self.TEXT_SIZE)
        reason_y = number_y - len(self._number_lines) * 14 - 2
        for i, line in enumerate(self._reason_lines):
            c.drawString(text_x, reason_y - i * self.LINE_H, line)

        # Action — arrowed, mint, wrapped
        c.setFillColor(self._MINT)
        c.setFont(self.TEXT_FONT, self.TEXT_SIZE)
        action_y = reason_y - len(self._reason_lines) * self.LINE_H - 2
        for i, line in enumerate(self._action_lines):
            c.drawString(text_x, action_y - i * self.LINE_H, line)

        c.restoreState()


class _AISkippedCard(Flowable):
    """Placeholder card shown when AI insights were skipped (free user, no API key)."""
    CARD_H = 80
    ACCENT_W = 4
    PAD_LEFT = 14
    PAD_TOP = 12

    _CARD_BG = HexColor('#F3F2F8')
    _AMBER = HexColor('#F59E0B')
    _INK = HexColor(INK)
    _GRAY = HexColor(MUTED)

    def __init__(self, width=None):
        Flowable.__init__(self)
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)

    def wrap(self, availWidth, availHeight):
        return (self._width, self.CARD_H)

    def draw(self):
        w = self._width
        y = self.CARD_H

        self.canv.setFillColor(self._CARD_BG)
        self.canv.roundRect(0, 0, w, self.CARD_H, radius=4, fill=1, stroke=0)

        self.canv.setFillColor(self._AMBER)
        self.canv.roundRect(0, 0, self.ACCENT_W, self.CARD_H, radius=2, fill=1, stroke=0)

        text_x = self.ACCENT_W + self.PAD_LEFT

        self.canv.setFillColor(self._INK)
        self.canv.setFont('IBMPlexSans-Bold', 9.5)
        self.canv.drawString(text_x, y - self.PAD_TOP - 9, "AI insights require an API key")

        self.canv.setFillColor(self._GRAY)
        self.canv.setFont('IBMPlexSans', 8)
        self.canv.drawString(text_x, y - self.PAD_TOP - 24, "Add your own API key in Settings \u2192 API Key to enable AI")
        self.canv.drawString(text_x, y - self.PAD_TOP - 36, "insights, or upgrade to Pro at naxely.com/billing")


class _AnomalyBox(Flowable):
    """Severity-tiered anomaly row — tinted panel + left accent + triangle-! marker, matching _InsightCard."""
    # Severity mapping mirrors _InsightCard: high→RUST, medium→#B45309, low→DELTA_UP
    _SEV_HEX = {
        "high": RUST,        # #A8481F
        "medium": "#B45309",
        "low": DELTA_UP,     # #5B7C55
    }
    _SEV_COLOR = {
        "high": HexColor(RUST),
        "medium": HexColor("#B45309"),
        "low": HexColor(DELTA_UP),
    }

    def __init__(self, anomaly, width=None):
        Flowable.__init__(self)
        # Backward-compat: allow passing plain string message
        if isinstance(anomaly, dict):
            self.message = _sanitize_for_pdf(str(anomaly.get("message", "Anomaly detected") or "Anomaly detected"))
            raw_z = anomaly.get("z_score", anomaly.get("deviation"))
        else:
            self.message = _sanitize_for_pdf(str(anomaly or "Anomaly detected"))
            raw_z = None
        # Derive severity from |z_score|; detector floor is |z|>2, so tiers are 2-3 low, 3-4 medium, >=4 high
        try:
            z = abs(float(raw_z)) if raw_z is not None else None
        except Exception:
            z = None
        if z is None:
            tier = "medium"  # fallback matching elsewhere (unknown → medium)
        elif z >= 4:
            tier = "high"
        elif z >= 3:
            tier = "medium"
        else:  # 2 <= z < 3 or z < 2 (should not happen as detector only emits >2, but handle)
            tier = "low"
        self.tier = tier
        self.severity_hex = self._SEV_HEX[tier]
        self.severity_color = self._SEV_COLOR[tier]
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.width = self._width
        # Allow up to 2 lines for longer plain-language messages (value + expected range)
        # Matching _InsightCard MAX_LINES=2 convention; truncate with … only if still too long after 2 lines
        self._message_lines = _fit_text_lines(self.message, 'IBMPlexSans', 9.5, self._width - 80, 2)
        # Base height 36 for 1 line; add LINE_H per extra line (same pattern as _InsightCard extra * LINE_H)
        base_h = 36
        line_h = 10
        extra = max(0, len(self._message_lines) - 1)
        self.height = base_h + extra * line_h

    def wrap(self, availWidth, availHeight):
        self.width = self._width
        # Recompute in case width changed; keep same logic as __init__
        # (ensures tint/accent don't render at zero height if wrap not assigning height)
        base_h = 36
        line_h = 10
        extra = max(0, len(getattr(self, '_message_lines', [])) - 1)
        self.height = base_h + extra * line_h
        return (self.width, self.height)

    def draw(self):
        c = self.canv
        c.saveState()
        w = self._width
        h = self.height
        # Tinted background — alpha 0.12, same as _InsightCard / _RecommendationCard tint
        tint = _brand_tint(self.severity_hex, alpha=0.12)
        c.setFillColor(tint)
        c.roundRect(0, 0, w, h, 6, fill=1, stroke=0)
        # Left accent strip — 5pt, matching _InsightCard
        c.setFillColor(self.severity_color)
        c.roundRect(0, 0, 5, h, 1.5, fill=1, stroke=0)
        # Ledger hairline below the row
        c.setStrokeColor(HexColor(RULE))
        c.setLineWidth(0.4)
        c.line(0, 0, w, 0)
        # Warning marker (triangle + '!') — keep custom path, color now tier-varying for contrast on tint
        c.setFillColor(self.severity_color)
        path = c.beginPath()
        path.moveTo(8, 10)
        path.lineTo(17, 10)
        path.lineTo(12.5, 19)
        path.close()
        c.drawPath(path, fill=1, stroke=0)
        c.setFillColor(white)
        c.setFont('IBMPlexSans-Bold', 6.5)
        c.drawCentredString(12.5, 11.2, '!')
        # Message text — RUST/DELTA_UP previously, now INK for readability on tint, tier color reserved for accent/marker/tag
        c.setFillColor(HexColor(INK))
        c.setFont('IBMPlexSans', 9.5)
        # Leave room for marker (0-22) and tag (w-52 to w-8) — available width ~ w-80
        # Allow up to 2 lines for longer plain-language messages (matching wrap); single line previously clipped at w-80
        lines = getattr(self, '_message_lines', _fit_text_lines(self.message, 'IBMPlexSans', 9.5, w - 80, 2))
        if len(lines) == 1:
            c.drawString(25, 14, lines[0] if lines else '')
        else:
            # Two lines: stack with LINE_H spacing, centered vertically in taller box
            c.drawString(25, 18, lines[0])
            c.drawString(25, 8, lines[1])
        # Severity tag — small HIGH/MEDIUM/LOW pill top-right, matching _InsightCard tag style
        tag_w = 44
        tag_h = 13
        tag_x = w - tag_w - 8
        tag_y = h - 10 - tag_h
        # Center vertically? Use top-right as in _InsightCard
        c.setFillColor(self.severity_color)
        c.roundRect(tag_x, tag_y, tag_w, tag_h, 6.5, fill=1, stroke=0)
        c.setFillColor(white)
        c.setFont('IBMPlexSans-Bold', 6.5)
        c.drawCentredString(tag_x + tag_w / 2, tag_y + 3, self.tier.upper())
        c.restoreState()


class _CoverBand(Flowable):
    def __init__(self, company_name, logo_path, brand_color_hex, white_label=False):
        Flowable.__init__(self)
        self.company_name = company_name
        self.logo_path = logo_path
        self.brand_color = HexColor(brand_color_hex)
        self.brand_color_hex = brand_color_hex
        self.white_label = white_label
        self.width = PAGE_WIDTH
        self.height = 72

    def wrap(self, availWidth, availHeight):
        return (self.width, self.height)

    def draw(self):
        self.canv.saveState()
        self.canv.translate(-MARGIN, 0)

        self.canv.setFillColor(HexColor('#FFFFFF'))
        self.canv.rect(0, -PAGE_HEIGHT, PAGE_WIDTH, PAGE_HEIGHT * 2, fill=1, stroke=0)

        glyph_x = 40
        glyph_y = 28

        if not self.white_label:
            bar_w = 3.5
            gap = 2.0
            heights = [8, 11, 15, 20]
            self.canv.setFillColor(self.brand_color)
            for i, h in enumerate(heights):
                bx = glyph_x + i * (bar_w + gap)
                self.canv.roundRect(bx, glyph_y, bar_w, h, 1, fill=1, stroke=0)

            wordmark_x = glyph_x + 4 * (bar_w + gap) + 6
            self.canv.setFont('IBMPlexSans', 9)
            self.canv.setFillColor(HexColor(MUTED))
            self.canv.drawString(wordmark_x, glyph_y + 3, 'Naxely')

        right_x = PAGE_WIDTH - 40
        if self.company_name:
            self.canv.setFont('IBMPlexSans', 9)
            self.canv.setFillColor(HexColor(MUTED))
            self.canv.drawRightString(right_x, glyph_y + 10, self.company_name)

        if self.logo_path:
            try:
                img_reader = ImageReader(self.logo_path)
                iw, ih = img_reader.getSize()
                scale = min(36 / ih, 110 / iw)
                draw_w = iw * scale
                draw_h = ih * scale
                logo_x = right_x - draw_w
                logo_y = glyph_y + 10 - draw_h - (16 if self.company_name else 0)
                self.canv.drawImage(
                    img_reader, logo_x, logo_y,
                    width=draw_w, height=draw_h,
                    mask='auto', preserveAspectRatio=True,
                )
            except Exception as e:
                logging.warning(f'[pdf_service] logo drawImage failed: {e}')

        self.canv.restoreState()


class _CoverMotif(Flowable):
    """Brand motif (3 ascending bars, common baseline) centred below the cover band."""
    def __init__(self, brand_color_hex):
        Flowable.__init__(self)
        self.brand_color = HexColor(brand_color_hex)
        self.content_size = 48  # 48×48 pt content area (uniform 2× favicon viewBox)
        self.width = PAGE_WIDTH
        self.height = self.content_size + 40  # 20pt pad above + below

    def wrap(self, availWidth, availHeight):
        return (self.width, self.height)

    def draw(self):
        self.canv.saveState()
        self.canv.translate(-MARGIN, 0)
        cx = self.width / 2
        area_left = cx - self.content_size / 2
        area_bottom = 20  # 20pt padding from bottom of flowable
        baseline = area_bottom + 4  # 4pt from area bottom = common bar baseline
        self.canv.setFillColor(self.brand_color)
        # Bars at uniform 2× from 24×24 viewBox; common baseline, ascending tops
        self.canv.roundRect(area_left + 4,    baseline, 11, 18,  2.4, fill=1, stroke=0)
        self.canv.roundRect(area_left + 18.5, baseline, 11, 29,  2.4, fill=1, stroke=0)
        self.canv.roundRect(area_left + 33,   baseline, 11, 40,  2.4, fill=1, stroke=0)
        self.canv.restoreState()


class _CoverRule(Flowable):
    """Horizontal rule — brand color, heavier weight."""
    def __init__(self, brand_color_hex):
        Flowable.__init__(self)
        self.brand_color = HexColor(brand_color_hex)
        self._width = PAGE_WIDTH - 2 * MARGIN
        self.height = 20

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        self.canv.saveState()
        self.canv.setStrokeColor(self.brand_color)
        self.canv.setLineWidth(1.2)
        self.canv.line(0, self.height / 2, self._width, self.height / 2)
        self.canv.restoreState()


def _strip_standard_fonts(pdf_path: str) -> None:
    """Remove unused standard PDF fonts from page Resources and their Tf
    operators from content streams, so the font listing is clean.

    Runs pikepdf in a subprocess with a 25-second timeout to prevent
    hanging on large PDFs. If it times out or fails, the original PDF
    is preserved.
    """
    script = r"""
import pikepdf
from pikepdf import parse_content_stream, unparse_content_stream, Operator

try:
    pdf = pikepdf.open(r"{path}", allow_overwriting_input=True)

    std = {{'/Helvetica', '/Helvetica-Bold', '/Helvetica-Oblique', '/Helvetica-BoldOblique',
           '/Times-Roman', '/Times-Bold', '/Times-Italic', '/Times-BoldItalic',
           '/Courier', '/Courier-Bold', '/Courier-Oblique', '/Courier-BoldOblique',
           '/Symbol', '/ZapfDingbats'}}

    page_std_keys = []
    for page in pdf.pages:
        fonts = page.get('/Resources', {{}}).get('/Font', pikepdf.Dictionary())
        keys = set()
        for key in fonts:
            try:
                if str(fonts[key].get('/BaseFont')) in std:
                    keys.add(str(key))
            except Exception:
                pass
        page_std_keys.append(keys)

    for page, std_keys in zip(pdf.pages, page_std_keys):
        if not std_keys:
            continue
        fonts = page.get('/Resources', {{}}).get('/Font', pikepdf.Dictionary())
        for key in list(fonts.keys()):
            if str(key) in std_keys:
                del fonts[key]
        cs = page.get('/Contents')
        if cs is not None:
            ops = parse_content_stream(cs)
            filtered = [(o, op) for o, op in ops
                        if not (op == Operator('Tf') and str(list(o)[0]) in std_keys)]
            cs.write(unparse_content_stream(filtered))

    import tempfile, shutil
    tmp = tempfile.mktemp(suffix='.pdf')
    pdf.save(tmp)
    pdf.close()
    shutil.move(tmp, r"{path}")
except Exception:
    import traceback
    traceback.print_exc()
    import sys
    sys.exit(1)
""".format(path=pdf_path)
    try:
        result = subprocess.run(
            [sys.executable, "-c", script],
            timeout=25,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            logging.warning(f"[pdf_service] font strip failed (rc={result.returncode}): {result.stderr[:200]}")
    except subprocess.TimeoutExpired:
        logging.warning("[pdf_service] font strip timed out after 25s — keeping original PDF")
    except Exception as e:
        logging.warning(f"[pdf_service] font strip error: {e}")


def _brand_tint(brand_hex, alpha=0.08):
    c = HexColor(brand_hex)
    r = c.red * alpha + 1.0 * (1.0 - alpha)
    g = c.green * alpha + 1.0 * (1.0 - alpha)
    b = c.blue * alpha + 1.0 * (1.0 - alpha)
    return Color(r, g, b)


class _RecommendationCard(Flowable):
    def __init__(self, index, text, brand_color_hex, width=None):
        Flowable.__init__(self)
        self.index = index
        self.text = text
        self.brand_color_hex = brand_color_hex
        self.brand_color = HexColor(brand_color_hex)
        self._full_width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.badge_size = 30
        self.badge_x = 12
        self.text_x = self.badge_x + self.badge_size + 12
        self.text_width = self._full_width - self.text_x - 12
        self.rec_style = ParagraphStyle(
            'RecCardText', fontName='IBMPlexSans', fontSize=10,
            textColor=HexColor(INK), leading=14,
            spaceBefore=0, spaceAfter=0,
        )
        self.para = Paragraph(text, self.rec_style)

    def wrap(self, availWidth, availHeight):
        _, ph = self.para.wrap(self.text_width, min(availHeight, 200))
        self._para_height = ph
        self.height = max(50, ph + 24)
        return (self._full_width, self.height)

    def draw(self):
        tint = _brand_tint(self.brand_color_hex, alpha=0.12)
        self.canv.setFillColor(self.brand_color)
        self.canv.roundRect(0, 0, 5, self.height, 1.5, fill=1, stroke=0)
        self.canv.setFillColor(tint)
        self.canv.roundRect(0, 0, self._full_width, self.height, 6, fill=1, stroke=0)
        bs, bx = self.badge_size, self.badge_x
        by = (self.height - bs) / 2
        self.canv.setFillColor(self.brand_color)
        self.canv.roundRect(bx, by, bs, bs, 15, fill=1, stroke=0)
        self.canv.setFillColor(white)
        self.canv.setFont('Fraunces-SemiBold', 16)
        self.canv.drawCentredString(bx + bs / 2, by + (bs - 16) / 2 + 2, str(self.index).zfill(2))
        para_y = (self.height - self._para_height) / 2
        self.para.drawOn(self.canv, self.text_x, para_y)


class _StatusPill(Flowable):
    """Compact pill for Status values — fits within 18pt row height."""
    def __init__(self, text, width=70):
        Flowable.__init__(self)
        raw = str(text) if text is not None else ''
        # keep truncation consistent with MAX_CELL_CHARS = 18
        self.text = _truncate_words(raw, 18)
        self.status = self.text.lower().strip()
        self.width = width
        self.height = 13
        self.font_name = 'IBMPlexSans-Bold'
        self.font_size = 7
        # color mapping: billed -> DELTA_UP solid with white text, pending/unknown -> neutral light gray with MUTED text
        if self.status == 'billed':
            self.bg = HexColor(DELTA_UP)
            self.text_color = HexColor('#FFFFFF')
        else:
            # pending or fallback — light neutral fill with muted text for legibility at small size
            # use _brand_tint(MUTED, alpha=0.12) blended light gray, or #E8E6E1
            self.bg = HexColor('#E8E6E1')
            self.text_color = HexColor(MUTED)
        # measure to ensure pill width fits text (use truncated text)
        text_w = pdfmetrics.stringWidth(self.text, self.font_name, self.font_size)
        # ensure width at least covers text + padding, but cap at 85 to stay within col
        self.width = min(max(text_w + 16, 50), 85)

    def wrap(self, availWidth, availHeight):
        return (self.width, self.height)

    def draw(self):
        c = self.canv
        w = self.width
        h = self.height
        c.saveState()
        c.setFillColor(self.bg)
        c.roundRect(0, 0, w, h, 6, fill=1, stroke=0)
        c.setFillColor(self.text_color)
        c.setFont(self.font_name, self.font_size)
        # uppercase for Billed/Pending for pill consistency, keep original for unknown
        display = self.text.upper() if self.status in ('billed', 'pending') else self.text
        c.drawCentredString(w/2, (h - self.font_size)/2 + 1, display)
        c.restoreState()


class _TocDot(Flowable):
    def __init__(self, color_hex, size=6):
        Flowable.__init__(self)
        self.color = HexColor(color_hex)
        self.size = size
        self.width = size
        self.height = size
    def wrap(self, availWidth, availHeight):
        return (self.width, self.height)
    def draw(self):
        self.canv.setFillColor(self.color)
        self.canv.circle(self.width/2, self.height/2, self.size/2, fill=1, stroke=0)


def _hex_to_reportlab(hex_str: str) -> HexColor:
    return HexColor(hex_str)


def _validate_url_scheme(url: str) -> None:
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme not in ("http", "https"):
        raise ValueError(f"URL scheme '{parsed.scheme}' is not allowed (only http/https)")


def _download_logo(logo_url: str) -> str | None:
    t0 = time.time()
    logging.info("[pdf_service] logo download start")
    try:
        _validate_url_scheme(logo_url)
        req = urllib.request.Request(logo_url, headers={'User-Agent': 'Naxely/1.0'})
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = resp.read()
        elapsed = round(time.time() - t0, 2)
        logging.info(f"[pdf_service] logo download done: {elapsed:.2f}s")

        img = PILImage.open(io.BytesIO(data)).convert('RGBA')

        # Resize logo to max height 36px (fits cleanly in cover band)
        max_h = 36
        if img.height > max_h:
            ratio = max_h / img.height
            img = img.resize((int(img.width * ratio), max_h), PILImage.Resampling.LANCZOS)

        # Add padding around the logo
        pad_x, pad_y = 12, 8
        badge_w = img.width + pad_x * 2
        badge_h = img.height + pad_y * 2

        # Create white background with rounded corners using PIL
        from PIL import ImageDraw
        badge = PILImage.new('RGBA', (badge_w, badge_h), (0, 0, 0, 0))
        draw = ImageDraw.Draw(badge)
        draw.rounded_rectangle(
            [(0, 0), (badge_w - 1, badge_h - 1)],
            radius=6,
            fill=(255, 255, 255, 255)
        )
        # Paste logo centered on badge
        badge.paste(img, (pad_x, pad_y), mask=img.split()[3])

        # Save as RGBA PNG with transparent corners (badge on transparent canvas)
        tmp = tempfile.NamedTemporaryFile(suffix='.png', delete=False)
        tmp_path = tmp.name
        tmp.close()
        badge.save(tmp_path, 'PNG')

        logging.info(f"[pdf_service] _download_logo success: {tmp_path}")
        return tmp_path
    except Exception as e:
        logging.warning(f"[pdf_service] _download_logo failed: {e}")
        return None


def _fmt_kpi_value(val: float, is_currency: bool = False) -> str:
    prefix = '$' if is_currency else ''
    if abs(val) >= 1_000_000:
        return f'{prefix}{val/1_000_000:.1f}M'
    if abs(val) >= 1_000:
        return f'{prefix}{val/1_000:.1f}K'
    if isinstance(val, float) and val != int(val):
        return f'{prefix}{val:.2f}'
    return f'{prefix}{int(val):,}'


def _add_watermark(canvas, doc):
    canvas.saveState()
    canvas.setFont('Fraunces-Medium', 50)
    canvas.setFillColor(Color(0, 0, 0, alpha=0.06))
    canvas.translate(PAGE_WIDTH / 2, PAGE_HEIGHT / 2)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, WATERMARK_TEXT)
    canvas.restoreState()


def _on_page(canvas, doc, add_watermark=False, is_white_label=False, is_free=False, company_name=''):
    canvas.saveState()
    canvas.setFillColor(HexColor(PAPER_BG))
    canvas.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)
    if is_white_label:
        canvas.setFont('IBMPlexSans', 8)
        canvas.setFillColor(HexColor(MUTED))
        if company_name:
            footer_text = f'{company_name} — {datetime.now().strftime("%B %d, %Y")}'
            canvas.drawString(MARGIN, 30, footer_text)
    elif is_free:
        canvas.setFont('IBMPlexSans', 9)
        canvas.setFillColor(HexColor(MUTED))
        canvas.drawString(MARGIN, 30, 'Made with Naxely — naxely.com')
    else:
        canvas.setFont('IBMPlexSans', 8)
        canvas.setFillColor(HexColor(MUTED))
        canvas.drawString(MARGIN, 30, f'Naxely Report — {datetime.now().strftime("%B %d, %Y")}')
    canvas.drawRightString(PAGE_WIDTH - MARGIN, 30, f'Page {doc.page}')
    if add_watermark:
        _add_watermark(canvas, doc)
    canvas.restoreState()


def _try_clean_numeric_series(series: pd.Series) -> pd.Series:
    from app.services.data_service import _try_clean_numeric
    return _try_clean_numeric(series)


def _is_percentage_col(col_name: str, series: pd.Series) -> bool:
    name = col_name.lower()
    if '%' in name or 'percent' in name or name.startswith('pct') or name.endswith('pct'):
        return True
    if 'rate' in name or 'ratio' in name:
        clean = _try_clean_numeric_series(series).dropna()
        if len(clean) == 0:
            return False
        if float(clean.max()) > 5:
            return False
        return True
    return False


def _is_currency_col(col_name: str, series: pd.Series) -> bool:
    name = col_name.lower()
    currency_keywords = ['amount', 'price', 'cost', 'fee', 'billable', 'revenue', 'salary', 'wage', 'budget', 'pay', 'hourly', 'rate']
    if any(kw in name for kw in currency_keywords):
        clean = _try_clean_numeric_series(series).dropna()
        if len(clean) > 0 and float(clean.max()) > 5:
            return True
    return False


def _is_per_unit_col(col_name: str) -> bool:
    name = col_name.lower()
    per_unit_keywords = ['rate', 'price', 'wage', 'hourly', 'per']
    return any(kw in name for kw in per_unit_keywords)


def _build_data_table(df: pd.DataFrame, brand_color: str, content_width: float) -> Table:
    def _hex_to_color(hex_str):
        hex_str = hex_str.lstrip('#')
        r, g, b = tuple(int(hex_str[i:i+2], 16) / 255.0 for i in (0, 2, 4))
        return colors.Color(r, g, b)

    even_row = _hex_to_color('#F2F1EB')
    odd_row = _hex_to_color(PAPER_BG)
    border = _hex_to_color(RULE)
    ink = _hex_to_color(INK)

    numeric_cols = set(
        c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])
    )
    date_cols = set(
        c for c in df.columns if pd.api.types.is_datetime64_any_dtype(df[c])
    )

    MAX_CELL_CHARS = 18
    def _fmt(val, col):
        if pd.isna(val):
            return ''
        if col in numeric_cols:
            if isinstance(val, float):
                return f'{val:,.2f}' if val != int(val) else f'{int(val):,}'
            return f'{val:,}'
        text = str(val)
        return _truncate_words(text, MAX_CELL_CHARS)

    # Identify Status column index (case-insensitive) for pill handling
    status_idx = None
    for idx, col in enumerate(df.columns):
        if str(col).lower() == 'status':
            status_idx = idx
            break

    headers = [str(col).upper() for col in df.columns]
    rows = []
    for _, row in df.iterrows():
        r = []
        for col in df.columns:
            val = row[col]
            if status_idx is not None and str(col).lower() == 'status':
                # Use pill Flowable for Status — keep truncation via _StatusPill
                r.append(_StatusPill(val))
            else:
                r.append(_fmt(val, col))
        rows.append(r)
    data = [headers] + rows

    # Size each column from the *actual rendered* cell text (exact font metrics)
    # rather than raw `astype(str)` samples: datetime64 → str drops the time
    # component and numeric str() lacks the thousands separators `_fmt` adds,
    # both of which used to under-size columns and make text spill sideways.
    MIN_W, MAX_W = 40, 130
    PAD = 6  # matches LEFTPADDING / RIGHTPADDING below
    HEADER_FONT, HEADER_SIZE = 'IBMPlexSans-Bold', 8
    CELL_FONT, CELL_SIZE = 'IBMPlexMono', 7.5
    col_widths = []
    for col in df.columns:
        if str(col).lower() == 'status':
            # Fixed width for pill — sized against longest known status plus padding, capped to MIN/MAX
            # Longest of Billed/Pending is 7 chars -> ~35pt at 7.5pt mono + padding
            hdr_w = pdfmetrics.stringWidth(str(col).upper(), HEADER_FONT, HEADER_SIZE)
            pill_w = pdfmetrics.stringWidth('PENDING', 'IBMPlexSans-Bold', 7) + 16
            w = min(MAX_W, max(MIN_W, max(hdr_w, pill_w) + 2 * PAD + 6))
            # Ensure at least 68 to fit pill comfortably, but respect MAX_W
            w = max(w, 68)
            w = min(w, 80)
            col_widths.append(w)
        else:
            samples = [_fmt(v, col) for v in df[col].dropna().head(20)]
            data_w = max(
                (pdfmetrics.stringWidth(s, CELL_FONT, CELL_SIZE) for s in samples),
                default=0.0,
            )
            hdr_w = pdfmetrics.stringWidth(str(col).upper(), HEADER_FONT, HEADER_SIZE)
            w = min(MAX_W, max(MIN_W, max(hdr_w, data_w) + 2 * PAD + 6))
            col_widths.append(w)

    total = sum(col_widths)
    if total > content_width:
        scale = content_width / total
        col_widths = [w * scale for w in col_widths]

    table = Table(data, colWidths=col_widths, repeatRows=1)

    muted = _hex_to_color(MUTED)
    rule_strong = _hex_to_color(RULE_STRONG)

    style_cmds = [
        # Plain uppercase mono column labels on PAPER — no colored band.
        ('FONTNAME', (0, 0), (-1, 0), 'IBMPlexMono'),
        ('FONTSIZE', (0, 0), (-1, 0), 8),
        ('TEXTCOLOR', (0, 0), (-1, 0), muted),
        ('FONTNAME', (0, 1), (-1, -1), 'IBMPlexMono'),
        ('FONTSIZE', (0, 1), (-1, -1), 7.5),
        ('TEXTCOLOR', (0, 1), (-1, -1), ink),
        ('ROWHEIGHT', (0, 0), (-1, -1), 18),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), PAD),
        ('RIGHTPADDING', (0, 0), (-1, -1), PAD),
        # Hairline rule beneath the header row, matching the section-header language.
        ('LINEBELOW', (0, 0), (-1, 0), 0.75, rule_strong),
        ('LINEBELOW', (0, 1), (-1, -1), 0.5, border),
        ('GRID', (0, 0), (-1, -1), 0, white),
    ]

    for i in range(1, len(data)):
        bg = even_row if i % 2 == 0 else odd_row
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))

    for j, col in enumerate(df.columns):
        if str(col).lower() == 'status':
            style_cmds.append(('ALIGN', (j, 1), (j, -1), 'CENTER'))
            style_cmds.append(('VALIGN', (j, 1), (j, -1), 'MIDDLE'))
        elif col in numeric_cols:
            style_cmds.append(('ALIGN', (j, 1), (j, -1), 'RIGHT'))
        elif col in date_cols:
            style_cmds.append(('ALIGN', (j, 1), (j, -1), 'CENTER'))
        else:
            style_cmds.append(('ALIGN', (j, 1), (j, -1), 'LEFT'))
        style_cmds.append(('ALIGN', (j, 0), (j, 0), 'CENTER'))

    table.setStyle(TableStyle(style_cmds))
    return table


def _compute_kpi_data(df: pd.DataFrame, config: dict, ai_content: dict, brand_color_hex: str) -> list[dict]:
    if config.get("_precomputed_kpis"):
        return config["_precomputed_kpis"]

    metric_cols = config.get('metric_columns', [])
    if not metric_cols:
        metric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    metric_cols = metric_cols[:5]

    from app.services.data_service import _compute_trend, _compute_trend_percentage, _try_clean_numeric

    kpis = []
    for col in metric_cols:
        if col not in df.columns:
            continue
        series = _try_clean_numeric(df[col]).dropna()
        if len(series) == 0:
            continue
        is_pct = _is_percentage_col(col, df[col])
        is_currency = not is_pct and _is_currency_col(col, df[col])
        is_per_unit = is_currency and _is_per_unit_col(col)
        if is_pct or is_per_unit:
            kpi_value = series.mean()
            prefix = 'Avg'
        else:
            kpi_value = series.sum()
            prefix = 'Total'
        trend = _compute_trend(series)
        trend_pct = _compute_trend_percentage(series, df, config.get("date_column"))
        has_date_col = bool(config.get("date_column"))
        trend_label = 'recent' if has_date_col else 'change'
        kpis.append({
            'name': f'{prefix} ' + col.replace('_', ' ').title(),
            'value': _fmt_kpi_value(kpi_value, is_currency) + ('%' if is_pct else ''),
            'trend': trend,
            'trend_pct': trend_pct,
            'trend_label': trend_label,
        })
    return kpis[:5]


def build_sync(
    df: pd.DataFrame,
    chart_paths: list[str] | list[tuple[str, str, str, str]],
    ai_content: dict,
    config: dict,
    user_data: dict,
) -> str:
    report_id = config.get('report_id', 'unknown')
    logging.info(f"[pdf_service] build_sync started — report_id={report_id}")
    brand_color = user_data.get('brand_color', BRAND_COLOR_DEFAULT)
    content_width = PAGE_WIDTH - 2 * MARGIN

    is_free = user_data.get('tier', 'free') == 'free'
    is_white_label = user_data.get('tier') == 'agency'
    company_name = user_data.get('company_name', '')

    output_dir = OUTPUT_ROOT / str(report_id)
    output_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = str(output_dir / 'report.pdf')

    def on_page(canvas, doc):
        _on_page(canvas, doc, add_watermark=is_free, is_white_label=is_white_label, is_free=is_free, company_name=company_name)

    def on_first_page(canvas, doc):
        canvas.saveState()
        bar_h = 8
        brand = HexColor(brand_color)
        canvas.setFillColor(brand)
        canvas.rect(0, PAGE_HEIGHT - bar_h, PAGE_WIDTH, bar_h, fill=1, stroke=0)
        canvas.rect(0, 0, PAGE_WIDTH, bar_h, fill=1, stroke=0)
        canvas.restoreState()
        _on_page(canvas, doc, add_watermark=is_free, is_white_label=is_white_label, is_free=is_free, company_name=company_name)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
    )

    body_style = ParagraphStyle(
        'BodyText2',
        fontName='IBMPlexSans',
        fontSize=10,
        textColor=HexColor(INK),
        alignment=TA_JUSTIFY,
        spaceAfter=8,
        leading=14,
    )

    toc_h1_style = ParagraphStyle(
        'TOCH1',
        fontName='IBMPlexSans',
        fontSize=11,
        textColor=HexColor('#374151'),
        leftIndent=20,
        spaceBefore=4,
        spaceAfter=2,
        leading=14,
    )

    story = []
    body_story: list = []
    # Two-pass TOC: markers record actual pages during first layout, then TOC is built with correct numbers
    toc_page_map: dict[str, int] = {}
    section_order: list[str] = []
    _TOC_LABELS: dict[str, str] = {
        'executive_summary': 'Executive Summary',
        'kpi_overview': 'Key Metrics Overview',
        'charts': 'Charts & Visualizations',
        'insights': 'AI Insights',
        'anomalies': 'Anomaly Flags',
        'data_table': 'Data Table',
        'recommendations': 'Recommendations',
        'appendix': 'Appendix — Raw Data',
    }

    # ────────────────────────────────────────────────────────────
    # SECTION 1 — Cover Page (into main story)
    # ────────────────────────────────────────────────────────────
    logo_path = None
    logo_signed_url = user_data.get('logo_url')
    if logo_signed_url:
        logo_path = _download_logo(logo_signed_url)

    title = config.get('title', 'Marketing Performance Report')
    company_name = user_data.get('company_name', '')

    story.append(_CoverBand(
        company_name=company_name,
        logo_path=logo_path,
        brand_color_hex=brand_color,
        white_label=is_white_label,
    ))
    story.append(Spacer(1, int(PAGE_HEIGHT * 0.10)))

    kpis = _compute_kpi_data(df, config, ai_content, brand_color)
    revenue_kpis = [k for k in kpis if 'revenue' in k.get('name', '').lower()]
    hero = max(revenue_kpis or kpis, key=lambda k: abs(k.get('trend_pct', 0))) if kpis else None

    if hero:
        trend_pct = hero['trend_pct']
        if trend_pct > 0:
            arrow_color_hex = brand_color
        elif trend_pct < 0:
            arrow_color_hex = RUST
        else:
            arrow_color_hex = MUTED
        sign = '+' if trend_pct > 0 else ''
        class _CoverHeroStat(Flowable):
            def __init__(self, hero, sign, trend_pct, arrow_color_hex, brand_color):
                Flowable.__init__(self)
                self.hero = hero
                self.sign = sign
                self.trend_pct = trend_pct
                self.arrow_color = HexColor(arrow_color_hex)
                self.brand_color = HexColor(brand_color)
                self.brand_color_hex = brand_color
                self._width = content_width
                self.height = 78
                self._font_size = 44

            def wrap(self, availWidth, availHeight):
                return (self._width, self.height)

            def draw(self):
                cx = self._width / 2
                label = f'{self.hero["name"]}: {self.sign}{self.trend_pct:.1f}%'
                font_name = 'Fraunces-SemiBold'
                font_size = self._font_size
                # background panel — low-opacity tint of brand_color (~12%)
                label_w = self.canv.stringWidth(label, font_name, font_size)
                arrow_gap = 18
                s = 10
                panel_w = label_w + s*2 + arrow_gap + 48
                panel_w = min(panel_w, self._width - 24)
                panel_h = 52
                panel_x = cx - panel_w / 2
                panel_y = 14
                self.canv.saveState()
                self.canv.setFillColor(_brand_tint(self.brand_color_hex, alpha=0.12))
                self.canv.roundRect(panel_x, panel_y, panel_w, panel_h, 10, fill=1, stroke=0)
                self.canv.restoreState()
                # label
                self.canv.setFillColor(self.brand_color)
                self.canv.setFont(font_name, font_size)
                self.canv.drawCentredString(cx, panel_y + 22, label)
                arrow_x = cx + label_w / 2 + arrow_gap
                arrow_y = panel_y + 30
                if self.trend_pct > 0:
                    p = self.canv.beginPath()
                    p.moveTo(arrow_x - s, arrow_y - s)
                    p.lineTo(arrow_x + s, arrow_y - s)
                    p.lineTo(arrow_x, arrow_y + s)
                    p.close()
                elif self.trend_pct < 0:
                    p = self.canv.beginPath()
                    p.moveTo(arrow_x - s, arrow_y + s)
                    p.lineTo(arrow_x + s, arrow_y + s)
                    p.lineTo(arrow_x, arrow_y - s)
                    p.close()
                else:
                    p = self.canv.beginPath()
                    p.moveTo(arrow_x - s, arrow_y - s)
                    p.lineTo(arrow_x - s, arrow_y + s)
                    p.lineTo(arrow_x + s, arrow_y)
                    p.close()
                self.canv.setFillColor(self.arrow_color)
                self.canv.drawPath(p, fill=1, stroke=0)
                qualifier = _trend_qualifier(self.hero.get('trend_label', ''))
                if qualifier:
                    self.canv.setFillColor(HexColor(MUTED))
                    self.canv.setFont('IBMPlexSans-Bold', 7.5)
                    self.canv.drawCentredString(cx, 4, qualifier)
        story.append(_CoverHeroStat(hero, sign, trend_pct, arrow_color_hex, brand_color))

    story.append(Spacer(1, 24))
    story.append(_CoverRule(brand_color))
    story.append(Spacer(1, 12))
    story.append(_CoverMotif(brand_color))
    story.append(Spacer(1, 12))

    title_style = ParagraphStyle(
        'CoverTitle',
        fontName='Fraunces-SemiBold',
        fontSize=26,
        textColor=HexColor(INK),
        alignment=TA_LEFT,
        leading=32,
        spaceAfter=8,
    )
    story.append(Paragraph(title or 'Data Analysis Report', title_style))

    subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        fontName='IBMPlexSans',
        fontSize=11,
        textColor=HexColor(MUTED),
        alignment=TA_LEFT,
        spaceAfter=24,
    )
    subtitle_text = company_name if company_name else 'Data Analysis Report'
    story.append(Paragraph(subtitle_text, subtitle_style))

    meta_style = ParagraphStyle(
        'CoverMeta',
        fontName='IBMPlexMono',
        fontSize=9,
        textColor=HexColor(MUTED),
        leading=13,
    )
    meta_style_right = ParagraphStyle(
        'CoverMetaRight',
        fontName='IBMPlexMono',
        fontSize=9,
        textColor=HexColor(MUTED),
        leading=13,
        alignment=TA_RIGHT,
    )

    date_from = config.get('date_from', 'N/A')
    date_to = config.get('date_to', 'N/A')
    date_text = ''
    if date_from and date_to and date_from != 'N/A':
        date_text = f'{date_from}  \u2013  {date_to}'

    prepared_by = (config.get('brand') or {}).get('prepared_by', '')
    right_text = ''
    if prepared_by:
        right_text = f'Prepared by {prepared_by}'
    else:
        right_text = datetime.now().strftime('%B %d, %Y')

    col_w = (PAGE_WIDTH - 2 * MARGIN) / 2
    meta_table = Table(
        [[Paragraph(date_text, meta_style), Paragraph(right_text, meta_style_right)]],
        colWidths=[col_w, col_w],
    )
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(meta_table)
    story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 2 — Executive Summary (merged with Key Metrics Overview)
    # ────────────────────────────────────────────────────────────
    has_exec = 'executive_summary' in config.get('sections', []) and ai_content.get('summary')
    has_kpi = 'kpi_overview' in config.get('sections', [])
    if has_exec:
        section_order.append('executive_summary')
        body_story.append(_TOCPageMarker('executive_summary', toc_page_map))
        body_story.append(_SectionHeader('Executive Summary', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        summary = ai_content['summary']
        if summary and summary.full_text.strip():
            # sanitize AI text for PDF font coverage (U+2011 etc → ASCII)
            lead_raw = _sanitize_for_pdf((summary.lead or '').lstrip())
            if lead_raw:
                lead_style = ParagraphStyle(
                    'SummaryLead',
                    fontName='Fraunces-Medium',
                    fontSize=13,
                    textColor=HexColor(INK),
                    leading=19,
                    spaceAfter=0,
                )
                first = lead_raw[0]
                rest = lead_raw[1:].lstrip()
                styled_lead = f'<font name="Fraunces-SemiBold" size="21">{first}</font>{rest}'
                lead_para = Paragraph(styled_lead, lead_style)
            else:
                lead_para = None

            # Key stat row — top 3 KPIs by absolute trend magnitude,
            # as a three-column ledger band with hairline dividers
            _kpis_for_strip = [k for k in (kpis or []) if k.get('trend_pct') is not None]
            _kpis_for_strip = sorted(
                _kpis_for_strip,
                key=lambda k: abs(k.get('trend_pct', 0)),
                reverse=True,
            )[:3]

            if _kpis_for_strip:
                stat_cols = []
                for k in _kpis_for_strip:
                    pct = k.get('trend_pct', 0) or 0
                    sign = '+' if pct >= 0 else ''
                    trend_color = brand_color if pct >= 0 else RUST
                    qualifier = _trend_qualifier(k.get('trend_label', ''))
                    trend_text = f"{sign}{pct:.1f}%" + (
                        f" ({qualifier})" if qualifier else ''
                    )
                    stat_cols.append([
                        Paragraph(str(k['name']).upper(), ParagraphStyle(
                            'StatName',
                            fontName='IBMPlexSans-Bold',
                            fontSize=7.5,
                            textColor=HexColor(MUTED),
                            alignment=TA_CENTER,
                            leading=9,
                        )),
                        Paragraph(str(k.get('value', '')), ParagraphStyle(
                            'StatValue',
                            fontName='IBMPlexMono-Bold',
                            fontSize=13,
                            textColor=HexColor(INK),
                            alignment=TA_CENTER,
                            leading=16,
                        )),
                        Paragraph(trend_text, ParagraphStyle(
                            'StatTrend',
                            fontName='IBMPlexSans-Bold',
                            fontSize=9,
                            textColor=HexColor(trend_color),
                            alignment=TA_CENTER,
                            leading=11,
                        )),
                    ])
                inner_w = content_width - 28
                col_w = inner_w / 3.0
                stat_table = Table(stat_cols, colWidths=[col_w] * 3, hAlign='CENTER')
                stat_table.setStyle(TableStyle([
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('LEFTPADDING', (0, 0), (-1, -1), 8),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                    ('TOPPADDING', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                    ('LINEABOVE', (0, 0), (-1, 0), 0.75, HexColor(RULE_STRONG)),
                    ('LINEBELOW', (0, -1), (-1, -1), 0.75, HexColor(RULE_STRONG)),
                    ('LINEBEFORE', (1, 0), (1, -1), 0.5, HexColor(RULE)),
                    ('LINEBEFORE', (2, 0), (2, -1), 0.5, HexColor(RULE)),
                ]))
            else:
                stat_table = None

            # Unified tinted panel for lead + stat strip (variable prose stays outside)
            panel_rows = []
            if lead_para is not None:
                panel_rows.append([lead_para])
            if stat_table is not None:
                panel_rows.append([stat_table])
            if panel_rows:
                if len(panel_rows) == 2:
                    panel_rows.insert(1, [Spacer(1, 8)])
                    panel_table = Table(panel_rows, colWidths=[content_width])
                else:
                    panel_table = Table(panel_rows, colWidths=[content_width])
                panel_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, -1), _brand_tint(brand_color, alpha=0.07)),
                    ('ROUNDEDCORNERS', [6, 6, 6, 6]),
                    ('LEFTPADDING', (0, 0), (-1, -1), 14),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 14),
                    ('TOPPADDING', (0, 0), (-1, -1), 14),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 14),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ]))
                body_story.append(panel_table)
                body_story.append(Spacer(1, 12))

            # Body prose — context, implication, action in sequence (sanitized)
            ctx = _sanitize_for_pdf(summary.context or '')
            imp = _sanitize_for_pdf(summary.implication or '')
            act = _sanitize_for_pdf(summary.action or '')
            body_parts = [ctx, imp, act]
            body_text = " ".join(p for p in body_parts if p.strip())
            if body_text:
                body_story.append(Paragraph(body_text, body_style))

        # Merge KPI grid into same page when both sections requested
        if has_kpi and kpis:
            # lightweight sub-heading for merged KPI block (not a full _SectionHeader)
            body_story.append(Spacer(1, 16))
            kpi_subhead_style = ParagraphStyle(
                'KPISubhead',
                fontName='IBMPlexSans-Bold',
                fontSize=11,
                textColor=HexColor(INK),
                leading=14,
                spaceAfter=8,
            )
            body_story.append(Paragraph('Key Metrics', kpi_subhead_style))
            body_story.extend(_build_kpi_grid_flowables(kpis, brand_color, content_width))
        body_story.append(PageBreak())
    elif has_kpi:
        # Standalone KPI page when executive_summary not requested — preserve data, don't silently drop
        section_order.append('kpi_overview')
        body_story.append(_TOCPageMarker('kpi_overview', toc_page_map))
        body_story.append(_SectionHeader('Key Metrics Overview', brand_color, content_width))
        body_story.append(Spacer(1, 10))
        if kpis:
            body_story.extend(_build_kpi_grid_flowables(kpis, brand_color, content_width))
        body_story.append(PageBreak())


    # ────────────────────────────────────────────────────────────
    # SECTION 4 — Charts
    # ────────────────────────────────────────────────────────────
    if 'charts' in config.get('sections', []):
        section_order.append('charts')
        body_story.append(_TOCPageMarker('charts', toc_page_map))
        body_story.append(_SectionHeader('Charts & Visualizations', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        rendered_charts = []
        for chart_item in chart_paths:
            if isinstance(chart_item, tuple):
                chart_path = chart_item[0]
                chart_caption = chart_item[2] if len(chart_item) > 2 else None
                chart_label = chart_item[3] if len(chart_item) > 3 else None
            else:
                chart_path = chart_item
                chart_caption = None
                chart_label = None
            if chart_path and os.path.isfile(chart_path):
                rendered_charts.append((chart_path, chart_caption, chart_label))

        chart_h = 200
        chart_gap = 16
        chart_label_style = ParagraphStyle(
            'ChartLabel',
            fontName='IBMPlexMono',
            fontSize=8.5,
            textColor=HexColor(INK),
            alignment=TA_CENTER,
            leading=11,
            spaceBefore=0,
            spaceAfter=2,
        )
        caption_style = ParagraphStyle(
            'ChartCaption',
            fontName='IBMPlexSans',
            fontSize=8.5,
            textColor=HexColor(MUTED),
            alignment=TA_CENTER,
            leading=11,
            spaceBefore=2,
            spaceAfter=2,
        )
        for i in range(0, len(rendered_charts), 2):
            pair = rendered_charts[i:i + 2]
            for j, (chart_path, chart_caption, chart_label) in enumerate(pair):
                try:
                    if chart_label:
                        body_story.append(Paragraph(chart_label.upper(), chart_label_style))
                    chart_img = Image(chart_path, width=content_width, height=chart_h)
                    chart_img.hAlign = 'CENTER'
                    body_story.append(chart_img)
                except Exception:
                    continue
                if chart_caption:
                    body_story.append(Paragraph(chart_caption, caption_style))
                if j < len(pair) - 1:
                    body_story.append(Spacer(1, chart_gap))
            body_story.append(Spacer(1, 10))
            if i + 2 < len(rendered_charts):
                body_story.append(PageBreak())

        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 5 — AI Insight Cards
    # ────────────────────────────────────────────────────────────
    insights = ai_content.get('insights') or []
    ai_skipped = config.get('_ai_skipped', False)
    if 'insights' in config.get('sections', []):
        section_order.append('insights')
        body_story.append(_TOCPageMarker('insights', toc_page_map))
        body_story.append(_SectionHeader('AI Insights', brand_color, content_width))
        body_story.append(Spacer(1, 6))
        if ai_skipped:
            body_story.append(_AISkippedCard(width=content_width))
            body_story.append(Spacer(1, 10))
        elif insights:
            for i, ins in enumerate(insights[:5], start=1):
                card = _InsightCard(ins, index=i, width=content_width)
                body_story.append(card)
                body_story.append(Spacer(1, 8))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 6 — Anomaly Flags
    # ────────────────────────────────────────────────────────────
    anomalies = ai_content.get('anomalies') or []
    if 'anomalies' in config.get('sections', []) and anomalies:
        section_order.append('anomalies')
        body_story.append(_TOCPageMarker('anomalies', toc_page_map))
        body_story.append(_SectionHeader('Anomaly Flags', brand_color, content_width))
        body_story.append(Spacer(1, 10))
        for anomaly in anomalies[:10]:
            box = _AnomalyBox(anomaly, width=content_width)
            body_story.append(box)
            body_story.append(Spacer(1, 6))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 7 — Data Table
    # ────────────────────────────────────────────────────────────
    if 'data_table' in config.get('sections', []):
        section_order.append('data_table')
        body_story.append(_TOCPageMarker('data_table', toc_page_map))
        body_story.append(_SectionHeader('Data Table', brand_color, content_width))
        body_story.append(Spacer(1, 10))
        # Provenance caption — honest row count from original df, date range from actual data, exclusion claim only if verifiable
        n_records = len(df)
        date_col = config.get('date_column')
        date_range_text = ''
        if date_col and date_col in df.columns:
            try:
                _dates = pd.to_datetime(df[date_col], errors='coerce').dropna()
                if len(_dates) >= 1:
                    _min = _dates.min()
                    _max = _dates.max()
                    date_range_text = f"{_min.strftime('%b %d, %Y')} \u2013 {_max.strftime('%b %d, %Y')}"
            except Exception:
                date_range_text = ''
        raw_nulls = config.get('_raw_null_counts') or {}
        is_clean = not any(v and int(v) > 0 for v in raw_nulls.values()) if isinstance(raw_nulls, dict) else True
        # Only claim "No records excluded" when we can verify no nulls/invalid rows and not truncated for display
        if date_range_text:
            if is_clean:
                _prov_text = f"Based on {n_records} records \u2022 {date_range_text} \u2022 No records excluded."
            else:
                _prov_text = f"Based on {n_records} records \u2022 {date_range_text}"
        else:
            if is_clean:
                _prov_text = f"Based on {n_records} records \u2022 No records excluded."
            else:
                _prov_text = f"Based on {n_records} records"
        _prov_style = ParagraphStyle('ProvenanceCaption', fontName='IBMPlexSans', fontSize=8, textColor=HexColor(MUTED), alignment=TA_CENTER, leading=11, spaceAfter=6)
        body_story.append(Paragraph(_prov_text, _prov_style))
        body_story.append(Spacer(1, 4))

        display_df = df.copy()
        if len(display_df) > 50:
            display_df = display_df.head(50)
        # Column cap: beyond 8 cols the table becomes illegible (see wide-table visual audit)
        MAX_DISPLAY_COLS = 8
        cols_truncated = None
        if len(display_df.columns) > MAX_DISPLAY_COLS:
            cols_truncated = len(display_df.columns)
            display_df = display_df.iloc[:, :MAX_DISPLAY_COLS]

        data_table = _build_data_table(display_df, brand_color, content_width)
        body_story.append(data_table)
        if cols_truncated is not None:
            note_style = ParagraphStyle('ColCapNote', fontName='IBMPlexSans', fontSize=7, textColor=HexColor(MUTED), alignment=TA_CENTER, leading=10, spaceBefore=6)
            body_story.append(Paragraph(f"Showing first {MAX_DISPLAY_COLS} of {cols_truncated} columns \u2014 see Excel export for full data.", note_style))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 8 — Recommendations
    # ────────────────────────────────────────────────────────────
    show_recommendations = (
        'insights' in config.get('sections', [])
        or 'executive_summary' in config.get('sections', [])
    ) and not ai_skipped
    if show_recommendations:
        section_order.append('recommendations')
        body_story.append(_TOCPageMarker('recommendations', toc_page_map))
        body_story.append(_SectionHeader('Recommendations', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        if ai_skipped:
            body_story.append(_AISkippedCard(width=content_width))
            body_story.append(Spacer(1, 10))
        else:
            recommendations = ai_content.get('recommendations') or []

            if recommendations:
                for idx, rec in enumerate(recommendations, 1):
                    body_story.append(_RecommendationCard(idx, rec, brand_color, content_width))
                    body_story.append(Spacer(1, 8))
            else:
                body_story.append(Paragraph('No recommendations available.', body_style))
            # Contact line — gated by prepared_by, no fallback, single appearance at end of Recommendations
            _prepared_by = (config.get('brand') or {}).get('prepared_by', '')
            if _prepared_by:
                _contact_style = ParagraphStyle('ContactLine', fontName='IBMPlexSans', fontSize=9, textColor=HexColor(MUTED), alignment=TA_CENTER, leading=12, spaceBefore=12)
                body_story.append(Paragraph(f'Questions about this report? Contact {_prepared_by}.', _contact_style))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 9 — Appendix
    # ────────────────────────────────────────────────────────────
    if 'appendix' in config.get('sections', []):
        section_order.append('appendix')
        body_story.append(_TOCPageMarker('appendix', toc_page_map))
        body_story.append(_SectionHeader('Appendix — Raw Data', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        appendix_df = df.copy()
        if len(appendix_df) > 100:
            appendix_df = appendix_df.head(100)
        MAX_APP_COLS = 8
        app_cols_truncated = None
        if len(appendix_df.columns) > MAX_APP_COLS:
            app_cols_truncated = len(appendix_df.columns)
            appendix_df = appendix_df.iloc[:, :MAX_APP_COLS]

        app_table_data = []
        app_header = [str(c).upper() for c in appendix_df.columns]
        app_table_data.append(app_header)
        for _, row in appendix_df.iterrows():
            app_table_data.append([str(v) if pd.notna(v) else '' for v in row])

        app_col_count = len(app_header)
        app_col_width = min(content_width / max(app_col_count, 1), 120)
        app_col_widths = [app_col_width] * app_col_count

        app_table = Table(app_table_data, colWidths=app_col_widths, repeatRows=1)

        app_style_commands = [
            # Plain uppercase mono column labels on PAPER — no colored band.
            ('FONTNAME', (0, 0), (-1, 0), 'IBMPlexMono'),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('TEXTCOLOR', (0, 0), (-1, 0), HexColor(MUTED)),
            ('FONTNAME', (0, 1), (-1, -1), 'IBMPlexMono'),
            ('FONTSIZE', (0, 1), (-1, -1), 7),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor(GRID_LINE)),
            # Hairline rule beneath the header row, matching the section-header language.
            ('LINEBELOW', (0, 0), (-1, 0), 0.75, HexColor(RULE_STRONG)),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]
        for row_idx in range(1, len(app_table_data)):
            if row_idx % 2 == 0:
                app_style_commands.append(
                    ('BACKGROUND', (0, row_idx), (-1, row_idx), HexColor(ROW_ALT_COLOR))
                )

        app_table.setStyle(TableStyle(app_style_commands))
        body_story.append(app_table)
        if app_cols_truncated is not None:
            note_style2 = ParagraphStyle('AppColCapNote', fontName='IBMPlexSans', fontSize=7, textColor=HexColor(MUTED), alignment=TA_CENTER, leading=10, spaceBefore=6)
            body_story.append(Paragraph(f"Showing first {MAX_APP_COLS} of {app_cols_truncated} columns \u2014 see Excel export for full data.", note_style2))

    # ────────────────────────────────────────────────────────────
    # TOC — two-pass build: first pass collects actual page numbers via
    # _TOCPageMarker, second pass renders TOC with correct numbers.
    # Preserves all existing TOC styling; logo download and font stripping
    # intentionally only run once (final pass) per Phase 1 cost assessment.
    # ────────────────────────────────────────────────────────────
    cover_story = list(story)  # shallow copy of cover flowables built so far

    def _build_toc_block(entries: list[tuple[str, str]]) -> list:
        rows = []
        for label, pg in entries:
            rows.append([
                _TocDot(brand_color, size=6),
                Paragraph(label, ParagraphStyle(
                    'TOCLabel',
                    fontName='IBMPlexSans',
                    fontSize=10,
                    textColor=HexColor(INK),
                    leading=16,
                )),
                Paragraph(pg, ParagraphStyle(
                    'TOCPage',
                    fontName='IBMPlexMono',
                    fontSize=9,
                    textColor=HexColor(brand_color),
                    alignment=TA_RIGHT,
                    leading=16,
                )),
            ])
        col_w2 = content_width
        table = Table(rows, colWidths=[12, col_w2 * 0.85 - 12, col_w2 * 0.15])
        table.setStyle(TableStyle([
            ('VALIGN',       (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING',  (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING',   (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING',(0, 0), (-1, -1), 5),
            ('LINEBELOW', (0, 0), (-1, -2), 0.4, HexColor(GRID_LINE)),
        ]))
        return [_SectionHeader('Table of Contents', brand_color, content_width), Spacer(1, 12), table, PageBreak()]

    # First pass: dummy TOC (same row count, '00' keeps pagination identical) to populate toc_page_map
    dummy_entries = [('Cover Page', '01'), ('Table of Contents', '02')] + [(_TOC_LABELS[k], '00') for k in section_order]
    toc_dummy_block = _build_toc_block(dummy_entries)
    import io as _io
    _temp_buf = _io.BytesIO()
    doc_temp = SimpleDocTemplate(_temp_buf, pagesize=A4, leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN, bottomMargin=MARGIN)
    story_temp = cover_story + toc_dummy_block + body_story
    try:
        doc_temp.build(story_temp, onFirstPage=on_first_page, onLaterPages=on_page)
    except Exception as e:
        logging.warning(f"[pdf_service] first pass TOC collection failed: {e}")

    # Build correct TOC from collected map (markers are zero-height, so pagination is stable)
    toc_entries: list[tuple[str, str]] = [('Cover Page', '01'), ('Table of Contents', '02')]
    for key in section_order:
        pg = toc_page_map.get(key)
        if pg is None:
            pg = 3 + section_order.index(key)
            logging.warning(f"[pdf_service] TOC marker missing for {key}, fallback to {pg}")
        toc_entries.append((_TOC_LABELS[key], str(pg).zfill(2)))

    toc_final_block = _build_toc_block(toc_entries)
    story_final = cover_story + toc_final_block + body_story

    # Final pass: reuse doc variable pointing at real pdf_path (logo_path already cached, not re-downloaded)
    doc = SimpleDocTemplate(pdf_path, pagesize=A4, leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN, bottomMargin=MARGIN)
    doc.build(story_final, onFirstPage=on_first_page, onLaterPages=on_page)
    logging.info(f"[pdf_service] build_sync completed (two-pass TOC) — report_id={report_id} pages_collected={toc_page_map}")

    _strip_standard_fonts(pdf_path)

    if logo_path:
        try:
            os.unlink(logo_path)
        except OSError:
            pass

    return pdf_path
