import logging
import os
import io

import subprocess
import sys
import time
import urllib.request
import tempfile
from datetime import datetime
from pathlib import Path

import pandas as pd
from PIL import Image as PILImage

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.lib.colors import HexColor, white, Color
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Frame,
    Spacer,
    Image,
    Table,
    TableStyle,
    PageBreak,
    Flowable,
)

PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN = 72
CHART_DPI = 150

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

FONT_DIR = Path(__file__).resolve().parent.parent / 'static' / 'fonts'
pdfmetrics.registerFont(TTFont('Fraunces-Medium', str(FONT_DIR / 'Fraunces-Medium.ttf')))
pdfmetrics.registerFont(TTFont('Fraunces-SemiBold', str(FONT_DIR / 'Fraunces-SemiBold.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexSans', str(FONT_DIR / 'IBMPlexSans-Regular.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexSans-Italic', str(FONT_DIR / 'IBMPlexSans-Italic.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexSans-Bold', str(FONT_DIR / 'IBMPlexSans-Bold.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexMono', str(FONT_DIR / 'IBMPlexMono-Regular.ttf')))
pdfmetrics.registerFont(TTFont('IBMPlexMono-Bold', str(FONT_DIR / 'IBMPlexMono-Bold.ttf')))
pdfmetrics.registerFontFamily('Fraunces', normal='Fraunces-Medium', bold='Fraunces-SemiBold')
pdfmetrics.registerFontFamily('IBMPlexSans', normal='IBMPlexSans', italic='IBMPlexSans-Italic')
pdfmetrics.registerFontFamily('IBMPlexMono', normal='IBMPlexMono', bold='IBMPlexMono-Bold')

from app.core.design_tokens import GRID_LINE

# ── Ledger design tokens ────────────────────────────────────────────────
INK = '#1A1D24'
PAPER_BG = '#FAFAF7'
RULE = '#D8D6CE'
RULE_STRONG = '#1A1D24'
MUTED = '#6B6E76'
RUST = '#A8481F'
DELTA_UP = '#5B7C55'   # muted ledger green for positive deltas (matches _InsightCard)

BRAND_COLOR_DEFAULT = '#D97A34'
ROW_ALT_COLOR = '#F2F1EB'
WATERMARK_TEXT = 'Generated by Naxely'

OUTPUT_ROOT = Path('/tmp/naxely')


class _SectionHeader(Flowable):
    def __init__(self, text, brand_color_hex, width=None):
        Flowable.__init__(self)
        self.text = text
        self.brand_color = HexColor(brand_color_hex)
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.height = 40

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        # Ledger section header: plain serif heading + hairline rule, no colored band.
        self.canv.setFillColor(HexColor(INK))
        self.canv.setFont('Fraunces-SemiBold', 20)
        self.canv.drawString(0, 22, self.text)
        self.canv.setStrokeColor(HexColor(RULE_STRONG))
        self.canv.setLineWidth(0.75)
        self.canv.line(0, 8, self._width, 8)


class _KPIRow(Flowable):
    """Ledger line-item for a single KPI: serif index, metric name, mono value,
    colored trend — hairline rules above and below the row."""

    def __init__(self, kpi, index, content_width, brand_color_hex):
        Flowable.__init__(self)
        self.kpi = kpi
        self.index = index
        self.brand_color_hex = brand_color_hex
        self._width = content_width
        self.height = 48

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        c = self.canv
        w = self._width
        h = self.height
        c.saveState()

        # hairlines above and below the ledger row
        c.setStrokeColor(HexColor(RULE))
        c.setLineWidth(0.4)
        c.line(0, 0, w, 0)
        c.line(0, h, w, h)

        # index — serif, muted
        c.setFillColor(HexColor(MUTED))
        c.setFont('Fraunces-Medium', 13)
        c.drawString(0, h - 30, str(self.index).zfill(2))

        # name — bold sans
        c.setFillColor(HexColor(INK))
        c.setFont('IBMPlexSans-Bold', 10)
        c.drawString(30, h - 18, str(self.kpi.get('name', '')))

        # value — mono bold, right of centre
        value = str(self.kpi.get('value', ''))
        c.setFillColor(HexColor(INK))
        c.setFont('IBMPlexMono-Bold', 14)
        c.drawRightString(w - 88, (h - 14) / 2 - 2, value)

        # trend — colored, far right. Colorblind-safe: arrow shape + sign +
        # color all carry direction, and up/down use the semantic ledger
        # mint/rust pair consistently with the AI insight cards.
        trend_pct = self.kpi.get('trend_pct', 0) or 0
        trend_color = DELTA_UP if trend_pct >= 0 else RUST
        sign = '+' if trend_pct >= 0 else '-'
        arrow = '\u2191' if trend_pct >= 0 else '\u2193'
        c.setFillColor(HexColor(trend_color))
        c.setFont('IBMPlexSans-Bold', 9)
        c.drawRightString(w, (h - 9) / 2 - 2,
                          f"{arrow} {sign} {abs(trend_pct):.1f}%")

        # qualifier under the trend — labels which calculation produced the
        # % (monthly-aggregate trend vs raw first-to-last), so the card never
        # silently contradicts a chart caption that uses the other measure
        qualifier = _trend_qualifier(self.kpi.get('trend_label', ''))
        if qualifier:
            c.setFillColor(HexColor(MUTED))
            c.setFont('IBMPlexSans-Bold', 6.5)
            c.drawRightString(w, 3, qualifier)

        c.restoreState()


def _wrap_text_lines(text: str, font_name: str, font_size: float, max_width: float) -> list[str]:
    """Greedy word wrap of `text` to `max_width` at the given font. Returns a
    list of lines, each fitting the box; an unbreakable word wider than the box
    is emitted alone rather than dropped."""
    lines, cur = [], ''
    for word in text.split(' '):
        trial = f'{cur} {word}'.strip()
        if cur and pdfmetrics.stringWidth(trial, font_name, font_size) > max_width:
            lines.append(cur)
            cur = word
        else:
            cur = trial
    if cur:
        lines.append(cur)
    return lines


def _fit_text_lines(text: str, font_name: str, font_size: float, max_width: float, max_lines: int) -> list[str]:
    """Wrap `text` to at most `max_lines` lines that fit `max_width`. When the
    text is longer, the final line is truncated at a word boundary with '…'
    rather than cutting mid-word."""
    lines = _wrap_text_lines(text, font_name, font_size, max_width)
    if len(lines) <= max_lines:
        return lines
    head = lines[:max_lines - 1]
    words = ' '.join(lines[max_lines - 1:]).split(' ')
    for n in range(len(words), 0, -1):
        candidate = ' '.join(words[:n]) + '\u2026'
        if pdfmetrics.stringWidth(candidate, font_name, font_size) <= max_width:
            return head + [candidate]
    return head + ['\u2026']


def _trend_qualifier(label: str) -> str:
    """Human-readable qualifier for a KPI trend %. Maps the machine
    `trend_label` ('recent' = monthly-aggregate trend, 'change' = raw
    first-to-last) to the phrase printed under the Key Metrics %."""
    return {
        'recent': 'monthly trend',
        'change': 'first-to-last',
    }.get(label, label)


def _truncate_words(text: str, limit: int) -> str:
    """Truncate `text` to at most `limit` characters at a word boundary,
    appending '…' — the char-based analogue of `_fit_text_lines` used where a
    fixed budget (table cells) applies. A single unbreakable word wider than
    the budget is cut at the limit rather than dropped."""
    if len(text) <= limit:
        return text
    words = text.split(' ')
    for n in range(len(words), 0, -1):
        candidate = ' '.join(words[:n])
        if len(candidate) <= limit - 1:
            return candidate + '\u2026'
    return text[:limit - 1] + '\u2026'


class _InsightCard(Flowable):
    """Ledger insight row: serif index, KPI name, severity tag, mono number,
    reason, and an arrowed action — hairline rule below the row. Long
    reason/action text wraps to a second line instead of being clipped
    mid-word; anything still over budget truncates at a word boundary."""

    CARD_H = 84
    LINE_H = 10
    PAD_LEFT = 30
    PAD_TOP = 12
    PAD_RIGHT = 8
    TAG_W = 44
    TAG_H = 13
    TEXT_FONT = 'IBMPlexSans'
    TEXT_SIZE = 8
    MAX_LINES = 2

    _MINT = HexColor(DELTA_UP)
    _RED = HexColor(RUST)
    _AMBER = HexColor('#B45309')
    _INK = HexColor(INK)
    _GRAY = HexColor(MUTED)
    _WHITE = HexColor('#FFFFFF')

    _PRIORITY_COLORS = {
        'high': _RED,
        'medium': _AMBER,
        'low': _MINT,
    }

    def __init__(self, insight, index=1, width=None):
        Flowable.__init__(self)
        self.insight = insight
        self.index = index
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        self._reason_lines = []
        self._action_lines = []
        self._layout_text()

    def _layout_text(self):
        ins = self.insight
        reason = str(ins.get('reason', '') or '')
        action = str(ins.get('action', '') or '')
        avail_w = self._width - self.PAD_LEFT - self.PAD_RIGHT
        self._reason_lines = _fit_text_lines(
            reason, self.TEXT_FONT, self.TEXT_SIZE, avail_w, self.MAX_LINES)
        self._action_lines = _fit_text_lines(
            '\u2192 ' + action, self.TEXT_FONT, self.TEXT_SIZE, avail_w, self.MAX_LINES)

    def wrap(self, availWidth, availHeight):
        extra = (len(self._reason_lines) - 1) + (len(self._action_lines) - 1)
        return (self._width, self.CARD_H + extra * self.LINE_H)

    def draw(self):
        ins = self.insight
        kpi = str(ins.get('kpi', '') or '')
        number = str(ins.get('number', '') or '')
        priority = str(ins.get('priority', 'medium')).lower()

        priority_color = self._PRIORITY_COLORS.get(priority, self._AMBER)
        w = self._width
        c = self.canv
        h = self.height
        c.saveState()

        # hairline below the ledger row
        c.setStrokeColor(HexColor(RULE))
        c.setLineWidth(0.4)
        c.line(0, 0, w, 0)

        # index — serif, muted
        c.setFillColor(self._GRAY)
        c.setFont('Fraunces-Medium', 14)
        c.drawString(0, h - 26, str(self.index).zfill(2))

        text_x = self.PAD_LEFT

        # KPI name
        c.setFillColor(self._INK)
        c.setFont('IBMPlexSans-Bold', 9.5)
        c.drawString(text_x, h - self.PAD_TOP - 8, kpi)

        # Severity tag (top right)
        tag_x = w - self.TAG_W - self.PAD_RIGHT
        tag_y = h - self.PAD_TOP - 11
        c.setFillColor(priority_color)
        c.roundRect(tag_x, tag_y, self.TAG_W, self.TAG_H, 6.5, fill=1, stroke=0)
        c.setFillColor(self._WHITE)
        c.setFont('IBMPlexSans-Bold', 6.5)
        c.drawCentredString(tag_x + self.TAG_W / 2, tag_y + 3, priority.upper())

        # Number — mono bold
        c.setFillColor(self._INK)
        c.setFont('IBMPlexMono-Bold', 13)
        c.drawString(text_x, h - self.PAD_TOP - 24, number)

        # Reason — wrapped, muted
        c.setFillColor(self._GRAY)
        c.setFont(self.TEXT_FONT, self.TEXT_SIZE)
        reason_y = h - self.PAD_TOP - 39
        for i, line in enumerate(self._reason_lines):
            c.drawString(text_x, reason_y - i * self.LINE_H, line)

        # Action — arrowed, mint, wrapped
        c.setFillColor(self._MINT)
        c.setFont(self.TEXT_FONT, self.TEXT_SIZE)
        action_y = reason_y - len(self._reason_lines) * self.LINE_H
        for i, line in enumerate(self._action_lines):
            c.drawString(text_x, action_y - i * self.LINE_H, line)

        c.restoreState()


class _AISkippedCard(Flowable):
    """Placeholder card shown when AI insights were skipped (free user, no API key)."""
    CARD_H = 80
    ACCENT_W = 4
    PAD_LEFT = 14
    PAD_TOP = 12

    _CARD_BG = HexColor('#F3F2F8')
    _AMBER = HexColor('#F59E0B')
    _INK = HexColor(INK)
    _GRAY = HexColor(MUTED)

    def __init__(self, width=None):
        Flowable.__init__(self)
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)

    def wrap(self, availWidth, availHeight):
        return (self._width, self.CARD_H)

    def draw(self):
        w = self._width
        y = self.CARD_H

        self.canv.setFillColor(self._CARD_BG)
        self.canv.roundRect(0, 0, w, self.CARD_H, radius=4, fill=1, stroke=0)

        self.canv.setFillColor(self._AMBER)
        self.canv.roundRect(0, 0, self.ACCENT_W, self.CARD_H, radius=2, fill=1, stroke=0)

        text_x = self.ACCENT_W + self.PAD_LEFT

        self.canv.setFillColor(self._INK)
        self.canv.setFont('IBMPlexSans-Bold', 9.5)
        self.canv.drawString(text_x, y - self.PAD_TOP - 9, "AI insights require an API key")

        self.canv.setFillColor(self._GRAY)
        self.canv.setFont('IBMPlexSans', 8)
        self.canv.drawString(text_x, y - self.PAD_TOP - 24, "Add your own API key in Settings \u2192 API Key to enable AI")
        self.canv.drawString(text_x, y - self.PAD_TOP - 36, "insights, or upgrade to Pro at naxely.com/billing")


class _AnomalyBox(Flowable):
    def __init__(self, message, width=None):
        Flowable.__init__(self)
        self.message = message
        self._width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.height = 28

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        c = self.canv
        c.saveState()
        # ledger hairline below the row
        c.setStrokeColor(HexColor(RULE))
        c.setLineWidth(0.4)
        c.line(0, 0, self._width, 0)
        # warning marker (triangle + '!') — U+26A0 is not covered by IBM Plex, so draw it
        c.setFillColor(HexColor(RUST))
        path = c.beginPath()
        path.moveTo(3, 4)
        path.lineTo(12, 4)
        path.lineTo(7.5, 13)
        path.close()
        c.drawPath(path, fill=1, stroke=0)
        c.setFillColor(white)
        c.setFont('IBMPlexSans-Bold', 6.5)
        c.drawCentredString(7.5, 5.2, '!')
        c.setFillColor(HexColor(RUST))
        c.setFont('IBMPlexSans', 9.5)
        lines = _fit_text_lines(self.message, 'IBMPlexSans', 9.5, self._width - 20, 1)
        c.drawString(20, 9, lines[0] if lines else '')
        c.restoreState()


class _CoverBand(Flowable):
    def __init__(self, company_name, logo_path, brand_color_hex, white_label=False):
        Flowable.__init__(self)
        self.company_name = company_name
        self.logo_path = logo_path
        self.brand_color = HexColor(brand_color_hex)
        self.brand_color_hex = brand_color_hex
        self.white_label = white_label
        self.width = PAGE_WIDTH
        self.height = 72

    def wrap(self, availWidth, availHeight):
        return (self.width, self.height)

    def draw(self):
        self.canv.saveState()
        self.canv.translate(-MARGIN, 0)

        self.canv.setFillColor(HexColor('#FFFFFF'))
        self.canv.rect(0, -PAGE_HEIGHT, PAGE_WIDTH, PAGE_HEIGHT * 2, fill=1, stroke=0)

        glyph_x = 40
        glyph_y = 28

        if not self.white_label:
            bar_w = 3.5
            gap = 2.0
            heights = [8, 11, 15, 20]
            self.canv.setFillColor(self.brand_color)
            for i, h in enumerate(heights):
                bx = glyph_x + i * (bar_w + gap)
                self.canv.roundRect(bx, glyph_y, bar_w, h, 1, fill=1, stroke=0)

            wordmark_x = glyph_x + 4 * (bar_w + gap) + 6
            self.canv.setFont('IBMPlexSans', 9)
            self.canv.setFillColor(HexColor(MUTED))
            self.canv.drawString(wordmark_x, glyph_y + 3, 'Naxely')

        right_x = PAGE_WIDTH - 40
        if self.company_name:
            self.canv.setFont('IBMPlexSans', 9)
            self.canv.setFillColor(HexColor(MUTED))
            self.canv.drawRightString(right_x, glyph_y + 10, self.company_name)

        if self.logo_path:
            try:
                img_reader = ImageReader(self.logo_path)
                iw, ih = img_reader.getSize()
                scale = min(36 / ih, 110 / iw)
                draw_w = iw * scale
                draw_h = ih * scale
                logo_x = right_x - draw_w
                logo_y = glyph_y + 10 - draw_h - (16 if self.company_name else 0)
                self.canv.drawImage(
                    img_reader, logo_x, logo_y,
                    width=draw_w, height=draw_h,
                    mask='auto', preserveAspectRatio=True,
                )
            except Exception as e:
                logging.warning(f'[pdf_service] logo drawImage failed: {e}')

        self.canv.restoreState()


class _CoverMotif(Flowable):
    """Brand motif (3 ascending bars, common baseline) centred below the cover band."""
    def __init__(self, brand_color_hex):
        Flowable.__init__(self)
        self.brand_color = HexColor(brand_color_hex)
        self.content_size = 48  # 48×48 pt content area (uniform 2× favicon viewBox)
        self.width = PAGE_WIDTH
        self.height = self.content_size + 40  # 20pt pad above + below

    def wrap(self, availWidth, availHeight):
        return (self.width, self.height)

    def draw(self):
        self.canv.saveState()
        self.canv.translate(-MARGIN, 0)
        cx = self.width / 2
        area_left = cx - self.content_size / 2
        area_bottom = 20  # 20pt padding from bottom of flowable
        baseline = area_bottom + 4  # 4pt from area bottom = common bar baseline
        self.canv.setFillColor(self.brand_color)
        # Bars at uniform 2× from 24×24 viewBox; common baseline, ascending tops
        self.canv.roundRect(area_left + 4,    baseline, 11, 18,  2.4, fill=1, stroke=0)
        self.canv.roundRect(area_left + 18.5, baseline, 11, 29,  2.4, fill=1, stroke=0)
        self.canv.roundRect(area_left + 33,   baseline, 11, 40,  2.4, fill=1, stroke=0)
        self.canv.restoreState()


class _CoverRule(Flowable):
    """Horizontal rule — brand color, heavier weight."""
    def __init__(self, brand_color_hex):
        Flowable.__init__(self)
        self.brand_color = HexColor(brand_color_hex)
        self._width = PAGE_WIDTH - 2 * MARGIN
        self.height = 20

    def wrap(self, availWidth, availHeight):
        return (self._width, self.height)

    def draw(self):
        self.canv.saveState()
        self.canv.setStrokeColor(self.brand_color)
        self.canv.setLineWidth(1.2)
        self.canv.line(0, self.height / 2, self._width, self.height / 2)
        self.canv.restoreState()


def _strip_standard_fonts(pdf_path: str) -> None:
    """Remove unused standard PDF fonts from page Resources and their Tf
    operators from content streams, so the font listing is clean.

    Runs pikepdf in a subprocess with a 25-second timeout to prevent
    hanging on large PDFs. If it times out or fails, the original PDF
    is preserved.
    """
    script = r"""
import pikepdf
from pikepdf import parse_content_stream, unparse_content_stream, Operator

try:
    pdf = pikepdf.open(r"{path}", allow_overwriting_input=True)

    std = {{'/Helvetica', '/Helvetica-Bold', '/Helvetica-Oblique', '/Helvetica-BoldOblique',
           '/Times-Roman', '/Times-Bold', '/Times-Italic', '/Times-BoldItalic',
           '/Courier', '/Courier-Bold', '/Courier-Oblique', '/Courier-BoldOblique',
           '/Symbol', '/ZapfDingbats'}}

    page_std_keys = []
    for page in pdf.pages:
        fonts = page.get('/Resources', {{}}).get('/Font', pikepdf.Dictionary())
        keys = set()
        for key in fonts:
            try:
                if str(fonts[key].get('/BaseFont')) in std:
                    keys.add(str(key))
            except Exception:
                pass
        page_std_keys.append(keys)

    for page, std_keys in zip(pdf.pages, page_std_keys):
        if not std_keys:
            continue
        fonts = page.get('/Resources', {{}}).get('/Font', pikepdf.Dictionary())
        for key in list(fonts.keys()):
            if str(key) in std_keys:
                del fonts[key]
        cs = page.get('/Contents')
        if cs is not None:
            ops = parse_content_stream(cs)
            filtered = [(o, op) for o, op in ops
                        if not (op == Operator('Tf') and str(list(o)[0]) in std_keys)]
            cs.write(unparse_content_stream(filtered))

    import tempfile, shutil
    tmp = tempfile.mktemp(suffix='.pdf')
    pdf.save(tmp)
    pdf.close()
    shutil.move(tmp, r"{path}")
except Exception:
    import traceback
    traceback.print_exc()
    import sys
    sys.exit(1)
""".format(path=pdf_path)
    try:
        result = subprocess.run(
            [sys.executable, "-c", script],
            timeout=25,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            logging.warning(f"[pdf_service] font strip failed (rc={result.returncode}): {result.stderr[:200]}")
    except subprocess.TimeoutExpired:
        logging.warning("[pdf_service] font strip timed out after 25s — keeping original PDF")
    except Exception as e:
        logging.warning(f"[pdf_service] font strip error: {e}")


def _brand_tint(brand_hex, alpha=0.08):
    c = HexColor(brand_hex)
    r = c.red * alpha + 1.0 * (1.0 - alpha)
    g = c.green * alpha + 1.0 * (1.0 - alpha)
    b = c.blue * alpha + 1.0 * (1.0 - alpha)
    return Color(r, g, b)


class _RecommendationCard(Flowable):
    def __init__(self, index, text, brand_color_hex, width=None):
        Flowable.__init__(self)
        self.index = index
        self.text = text
        self.brand_color_hex = brand_color_hex
        self.brand_color = HexColor(brand_color_hex)
        self._full_width = width or (PAGE_WIDTH - 2 * MARGIN)
        self.badge_size = 30
        self.badge_x = 12
        self.text_x = self.badge_x + self.badge_size + 12
        self.text_width = self._full_width - self.text_x - 12
        self.rec_style = ParagraphStyle(
            'RecCardText', fontName='IBMPlexSans', fontSize=10,
            textColor=HexColor(INK), leading=14,
            spaceBefore=0, spaceAfter=0,
        )
        self.para = Paragraph(text, self.rec_style)

    def wrap(self, availWidth, availHeight):
        _, ph = self.para.wrap(self.text_width, min(availHeight, 200))
        self._para_height = ph
        self.height = max(50, ph + 24)
        return (self._full_width, self.height)

    def draw(self):
        tint = _brand_tint(self.brand_color_hex)
        self.canv.setFillColor(self.brand_color)
        self.canv.roundRect(0, 0, 3, self.height, 1.5, fill=1, stroke=0)
        self.canv.setFillColor(tint)
        self.canv.roundRect(0, 0, self._full_width, self.height, 6, fill=1, stroke=0)
        bs, bx = self.badge_size, self.badge_x
        by = (self.height - bs) / 2
        self.canv.setFillColor(self.brand_color)
        self.canv.roundRect(bx, by, bs, bs, 15, fill=1, stroke=0)
        self.canv.setFillColor(white)
        self.canv.setFont('Fraunces-SemiBold', 16)
        self.canv.drawCentredString(bx + bs / 2, by + (bs - 16) / 2 + 2, str(self.index).zfill(2))
        para_y = (self.height - self._para_height) / 2
        self.para.drawOn(self.canv, self.text_x, para_y)


def _hex_to_reportlab(hex_str: str) -> HexColor:
    return HexColor(hex_str)


def _validate_url_scheme(url: str) -> None:
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme not in ("http", "https"):
        raise ValueError(f"URL scheme '{parsed.scheme}' is not allowed (only http/https)")


def _download_logo(logo_url: str) -> str | None:
    t0 = time.time()
    logging.info("[pdf_service] logo download start")
    try:
        _validate_url_scheme(logo_url)
        req = urllib.request.Request(logo_url, headers={'User-Agent': 'Naxely/1.0'})
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = resp.read()
        elapsed = round(time.time() - t0, 2)
        logging.info(f"[pdf_service] logo download done: {elapsed:.2f}s")

        img = PILImage.open(io.BytesIO(data)).convert('RGBA')

        # Resize logo to max height 36px (fits cleanly in cover band)
        max_h = 36
        if img.height > max_h:
            ratio = max_h / img.height
            img = img.resize((int(img.width * ratio), max_h), PILImage.Resampling.LANCZOS)

        # Add padding around the logo
        pad_x, pad_y = 12, 8
        badge_w = img.width + pad_x * 2
        badge_h = img.height + pad_y * 2

        # Create white background with rounded corners using PIL
        from PIL import ImageDraw
        badge = PILImage.new('RGBA', (badge_w, badge_h), (0, 0, 0, 0))
        draw = ImageDraw.Draw(badge)
        draw.rounded_rectangle(
            [(0, 0), (badge_w - 1, badge_h - 1)],
            radius=6,
            fill=(255, 255, 255, 255)
        )
        # Paste logo centered on badge
        badge.paste(img, (pad_x, pad_y), mask=img.split()[3])

        # Save as RGBA PNG with transparent corners (badge on transparent canvas)
        tmp = tempfile.NamedTemporaryFile(suffix='.png', delete=False)
        tmp_path = tmp.name
        tmp.close()
        badge.save(tmp_path, 'PNG')

        logging.info(f"[pdf_service] _download_logo success: {tmp_path}")
        return tmp_path
    except Exception as e:
        logging.warning(f"[pdf_service] _download_logo failed: {e}")
        return None


def _fmt_kpi_value(val: float, is_currency: bool = False) -> str:
    prefix = '$' if is_currency else ''
    if abs(val) >= 1_000_000:
        return f'{prefix}{val/1_000_000:.1f}M'
    if abs(val) >= 1_000:
        return f'{prefix}{val/1_000:.1f}K'
    if isinstance(val, float) and val != int(val):
        return f'{prefix}{val:.2f}'
    return f'{prefix}{int(val):,}'


def _add_watermark(canvas, doc):
    canvas.saveState()
    canvas.setFont('Fraunces-Medium', 50)
    canvas.setFillColor(Color(0, 0, 0, alpha=0.06))
    canvas.translate(PAGE_WIDTH / 2, PAGE_HEIGHT / 2)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, WATERMARK_TEXT)
    canvas.restoreState()


def _on_page(canvas, doc, add_watermark=False, is_white_label=False, is_free=False, company_name=''):
    canvas.saveState()
    canvas.setFillColor(HexColor(PAPER_BG))
    canvas.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)
    if is_white_label:
        canvas.setFont('IBMPlexSans', 8)
        canvas.setFillColor(HexColor(MUTED))
        if company_name:
            footer_text = f'{company_name} — {datetime.now().strftime("%B %d, %Y")}'
            canvas.drawString(MARGIN, 30, footer_text)
    elif is_free:
        canvas.setFont('IBMPlexSans', 9)
        canvas.setFillColor(HexColor(MUTED))
        canvas.drawString(MARGIN, 30, 'Made with Naxely — naxely.com')
    else:
        canvas.setFont('IBMPlexSans', 8)
        canvas.setFillColor(HexColor(MUTED))
        canvas.drawString(MARGIN, 30, f'Naxely Report — {datetime.now().strftime("%B %d, %Y")}')
    canvas.drawRightString(PAGE_WIDTH - MARGIN, 30, f'Page {doc.page}')
    if add_watermark:
        _add_watermark(canvas, doc)
    canvas.restoreState()


def _try_clean_numeric_series(series: pd.Series) -> pd.Series:
    from app.services.data_service import _try_clean_numeric
    return _try_clean_numeric(series)


def _is_percentage_col(col_name: str, series: pd.Series) -> bool:
    name = col_name.lower()
    if '%' in name or 'percent' in name or name.startswith('pct') or name.endswith('pct'):
        return True
    if 'rate' in name or 'ratio' in name:
        clean = _try_clean_numeric_series(series).dropna()
        if len(clean) == 0:
            return False
        if float(clean.max()) > 5:
            return False
        return True
    return False


def _is_currency_col(col_name: str, series: pd.Series) -> bool:
    name = col_name.lower()
    currency_keywords = ['amount', 'price', 'cost', 'fee', 'billable', 'revenue', 'salary', 'wage', 'budget', 'pay', 'hourly', 'rate']
    if any(kw in name for kw in currency_keywords):
        clean = _try_clean_numeric_series(series).dropna()
        if len(clean) > 0 and float(clean.max()) > 5:
            return True
    return False


def _is_per_unit_col(col_name: str) -> bool:
    name = col_name.lower()
    per_unit_keywords = ['rate', 'price', 'wage', 'hourly', 'per']
    return any(kw in name for kw in per_unit_keywords)


def _build_data_table(df: pd.DataFrame, brand_color: str, content_width: float) -> Table:
    def _hex_to_color(hex_str):
        hex_str = hex_str.lstrip('#')
        r, g, b = tuple(int(hex_str[i:i+2], 16) / 255.0 for i in (0, 2, 4))
        return colors.Color(r, g, b)

    even_row = _hex_to_color('#F2F1EB')
    odd_row = _hex_to_color(PAPER_BG)
    border = _hex_to_color(RULE)
    ink = _hex_to_color(INK)

    numeric_cols = set(
        c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])
    )
    date_cols = set(
        c for c in df.columns if pd.api.types.is_datetime64_any_dtype(df[c])
    )

    MAX_CELL_CHARS = 18
    def _fmt(val, col):
        if pd.isna(val):
            return ''
        if col in numeric_cols:
            if isinstance(val, float):
                return f'{val:,.2f}' if val != int(val) else f'{int(val):,}'
            return f'{val:,}'
        text = str(val)
        return _truncate_words(text, MAX_CELL_CHARS)

    headers = [str(col).upper() for col in df.columns]
    rows = [[_fmt(row[col], col) for col in df.columns]
            for _, row in df.iterrows()]
    data = [headers] + rows

    # Size each column from the *actual rendered* cell text (exact font metrics)
    # rather than raw `astype(str)` samples: datetime64 → str drops the time
    # component and numeric str() lacks the thousands separators `_fmt` adds,
    # both of which used to under-size columns and make text spill sideways.
    MIN_W, MAX_W = 40, 130
    PAD = 6  # matches LEFTPADDING / RIGHTPADDING below
    HEADER_FONT, HEADER_SIZE = 'IBMPlexSans-Bold', 8
    CELL_FONT, CELL_SIZE = 'IBMPlexMono', 7.5
    col_widths = []
    for col in df.columns:
        samples = [_fmt(v, col) for v in df[col].dropna().head(20)]
        data_w = max(
            (pdfmetrics.stringWidth(s, CELL_FONT, CELL_SIZE) for s in samples),
            default=0.0,
        )
        hdr_w = pdfmetrics.stringWidth(str(col).upper(), HEADER_FONT, HEADER_SIZE)
        w = min(MAX_W, max(MIN_W, max(hdr_w, data_w) + 2 * PAD + 6))
        col_widths.append(w)

    total = sum(col_widths)
    if total > content_width:
        scale = content_width / total
        col_widths = [w * scale for w in col_widths]

    table = Table(data, colWidths=col_widths, repeatRows=1)

    muted = _hex_to_color(MUTED)
    rule_strong = _hex_to_color(RULE_STRONG)

    style_cmds = [
        # Plain uppercase mono column labels on PAPER — no colored band.
        ('FONTNAME', (0, 0), (-1, 0), 'IBMPlexMono'),
        ('FONTSIZE', (0, 0), (-1, 0), 8),
        ('TEXTCOLOR', (0, 0), (-1, 0), muted),
        ('FONTNAME', (0, 1), (-1, -1), 'IBMPlexMono'),
        ('FONTSIZE', (0, 1), (-1, -1), 7.5),
        ('TEXTCOLOR', (0, 1), (-1, -1), ink),
        ('ROWHEIGHT', (0, 0), (-1, -1), 18),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), PAD),
        ('RIGHTPADDING', (0, 0), (-1, -1), PAD),
        # Hairline rule beneath the header row, matching the section-header language.
        ('LINEBELOW', (0, 0), (-1, 0), 0.75, rule_strong),
        ('LINEBELOW', (0, 1), (-1, -1), 0.5, border),
        ('GRID', (0, 0), (-1, -1), 0, white),
    ]

    for i in range(1, len(data)):
        bg = even_row if i % 2 == 0 else odd_row
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))

    for j, col in enumerate(df.columns):
        if col in numeric_cols:
            style_cmds.append(('ALIGN', (j, 1), (j, -1), 'RIGHT'))
        elif col in date_cols:
            style_cmds.append(('ALIGN', (j, 1), (j, -1), 'CENTER'))
        else:
            style_cmds.append(('ALIGN', (j, 1), (j, -1), 'LEFT'))
        style_cmds.append(('ALIGN', (j, 0), (j, 0), 'CENTER'))

    table.setStyle(TableStyle(style_cmds))
    return table


def _compute_kpi_data(df: pd.DataFrame, config: dict, ai_content: dict, brand_color_hex: str) -> list[dict]:
    if config.get("_precomputed_kpis"):
        return config["_precomputed_kpis"]

    metric_cols = config.get('metric_columns', [])
    if not metric_cols:
        metric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    metric_cols = metric_cols[:5]

    from app.services.data_service import _compute_trend, _compute_trend_percentage, _try_clean_numeric

    kpis = []
    for col in metric_cols:
        if col not in df.columns:
            continue
        series = _try_clean_numeric(df[col]).dropna()
        if len(series) == 0:
            continue
        is_pct = _is_percentage_col(col, df[col])
        is_currency = not is_pct and _is_currency_col(col, df[col])
        is_per_unit = is_currency and _is_per_unit_col(col)
        if is_pct or is_per_unit:
            kpi_value = series.mean()
            prefix = 'Avg'
        else:
            kpi_value = series.sum()
            prefix = 'Total'
        trend = _compute_trend(series)
        trend_pct = _compute_trend_percentage(series, df, config.get("date_column"))
        has_date_col = bool(config.get("date_column"))
        trend_label = 'recent' if has_date_col else 'change'
        kpis.append({
            'name': f'{prefix} ' + col.replace('_', ' ').title(),
            'value': _fmt_kpi_value(kpi_value, is_currency) + ('%' if is_pct else ''),
            'trend': trend,
            'trend_pct': trend_pct,
            'trend_label': trend_label,
        })
    return kpis[:5]


def build_sync(
    df: pd.DataFrame,
    chart_paths: list[str],
    ai_content: dict,
    config: dict,
    user_data: dict,
) -> str:
    report_id = config.get('report_id', 'unknown')
    logging.info(f"[pdf_service] build_sync started — report_id={report_id}")
    brand_color = user_data.get('brand_color', BRAND_COLOR_DEFAULT)
    content_width = PAGE_WIDTH - 2 * MARGIN

    is_free = user_data.get('tier', 'free') == 'free'
    is_white_label = user_data.get('tier') == 'agency'
    company_name = user_data.get('company_name', '')

    output_dir = OUTPUT_ROOT / str(report_id)
    output_dir.mkdir(parents=True, exist_ok=True)
    pdf_path = str(output_dir / 'report.pdf')

    def on_page(canvas, doc):
        _on_page(canvas, doc, add_watermark=is_free, is_white_label=is_white_label, is_free=is_free, company_name=company_name)

    def on_first_page(canvas, doc):
        canvas.saveState()
        bar_h = 8
        brand = HexColor(brand_color)
        canvas.setFillColor(brand)
        canvas.rect(0, PAGE_HEIGHT - bar_h, PAGE_WIDTH, bar_h, fill=1, stroke=0)
        canvas.rect(0, 0, PAGE_WIDTH, bar_h, fill=1, stroke=0)
        canvas.restoreState()
        _on_page(canvas, doc, add_watermark=is_free, is_white_label=is_white_label, is_free=is_free, company_name=company_name)

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=MARGIN,
    )

    body_style = ParagraphStyle(
        'BodyText2',
        fontName='IBMPlexSans',
        fontSize=10,
        textColor=HexColor(INK),
        alignment=TA_JUSTIFY,
        spaceAfter=8,
        leading=14,
    )

    toc_h1_style = ParagraphStyle(
        'TOCH1',
        fontName='IBMPlexSans',
        fontSize=11,
        textColor=HexColor('#374151'),
        leftIndent=20,
        spaceBefore=4,
        spaceAfter=2,
        leading=14,
    )

    story = []
    body_story: list = []
    toc_entries = [('Cover Page', '01'), ('Table of Contents', '02')]
    toc_page = 3

    # ────────────────────────────────────────────────────────────
    # SECTION 1 — Cover Page (into main story)
    # ────────────────────────────────────────────────────────────
    logo_path = None
    logo_signed_url = user_data.get('logo_url')
    if logo_signed_url:
        logo_path = _download_logo(logo_signed_url)

    title = config.get('title', 'Marketing Performance Report')
    company_name = user_data.get('company_name', '')

    story.append(_CoverBand(
        company_name=company_name,
        logo_path=logo_path,
        brand_color_hex=brand_color,
        white_label=is_white_label,
    ))
    story.append(Spacer(1, int(PAGE_HEIGHT * 0.20)))

    kpis = _compute_kpi_data(df, config, ai_content, brand_color)
    revenue_kpis = [k for k in kpis if 'revenue' in k.get('name', '').lower()]
    hero = max(revenue_kpis or kpis, key=lambda k: abs(k.get('trend_pct', 0))) if kpis else None

    if hero:
        trend_pct = hero['trend_pct']
        if trend_pct > 0:
            arrow_color_hex = brand_color
        elif trend_pct < 0:
            arrow_color_hex = RUST
        else:
            arrow_color_hex = MUTED
        sign = '+' if trend_pct > 0 else ''
        class _CoverHeroStat(Flowable):
            def __init__(self, hero, sign, trend_pct, arrow_color_hex, brand_color):
                Flowable.__init__(self)
                self.hero = hero
                self.sign = sign
                self.trend_pct = trend_pct
                self.arrow_color = HexColor(arrow_color_hex)
                self.brand_color = HexColor(brand_color)
                self._width = content_width
                self.height = 56

            def wrap(self, availWidth, availHeight):
                return (self._width, self.height)

            def draw(self):
                cx = self._width / 2
                label = f'{self.hero["name"]}: {self.sign}{self.trend_pct:.1f}%'
                self.canv.setFillColor(self.brand_color)
                self.canv.setFont('Fraunces-SemiBold', 22)
                self.canv.drawCentredString(cx, 18, label)
                s = 9
                arrow_x = cx + self.canv.stringWidth(label, 'Fraunces-SemiBold', 22) / 2 + 16
                arrow_y = 28
                if self.trend_pct > 0:
                    p = self.canv.beginPath()
                    p.moveTo(arrow_x - s, arrow_y - s)
                    p.lineTo(arrow_x + s, arrow_y - s)
                    p.lineTo(arrow_x, arrow_y + s)
                    p.close()
                elif self.trend_pct < 0:
                    p = self.canv.beginPath()
                    p.moveTo(arrow_x - s, arrow_y + s)
                    p.lineTo(arrow_x + s, arrow_y + s)
                    p.lineTo(arrow_x, arrow_y - s)
                    p.close()
                else:
                    p = self.canv.beginPath()
                    p.moveTo(arrow_x - s, arrow_y - s)
                    p.lineTo(arrow_x - s, arrow_y + s)
                    p.lineTo(arrow_x + s, arrow_y)
                    p.close()
                self.canv.setFillColor(self.arrow_color)
                self.canv.drawPath(p, fill=1, stroke=0)
                qualifier = _trend_qualifier(self.hero.get('trend_label', ''))
                if qualifier:
                    self.canv.setFillColor(HexColor(MUTED))
                    self.canv.setFont('IBMPlexSans-Bold', 7.5)
                    self.canv.drawCentredString(cx, 4, qualifier)
        story.append(_CoverHeroStat(hero, sign, trend_pct, arrow_color_hex, brand_color))

    story.append(Spacer(1, 24))
    story.append(_CoverRule(brand_color))

    title_style = ParagraphStyle(
        'CoverTitle',
        fontName='Fraunces-SemiBold',
        fontSize=26,
        textColor=HexColor(INK),
        alignment=TA_LEFT,
        leading=32,
        spaceAfter=8,
    )
    story.append(Paragraph(title or 'Data Analysis Report', title_style))

    subtitle_style = ParagraphStyle(
        'CoverSubtitle',
        fontName='IBMPlexSans',
        fontSize=11,
        textColor=HexColor(MUTED),
        alignment=TA_LEFT,
        spaceAfter=24,
    )
    subtitle_text = company_name if company_name else 'Data Analysis Report'
    story.append(Paragraph(subtitle_text, subtitle_style))

    meta_style = ParagraphStyle(
        'CoverMeta',
        fontName='IBMPlexMono',
        fontSize=9,
        textColor=HexColor(MUTED),
        leading=13,
    )
    meta_style_right = ParagraphStyle(
        'CoverMetaRight',
        fontName='IBMPlexMono',
        fontSize=9,
        textColor=HexColor(MUTED),
        leading=13,
        alignment=TA_RIGHT,
    )

    date_from = config.get('date_from', 'N/A')
    date_to = config.get('date_to', 'N/A')
    date_text = ''
    if date_from and date_to and date_from != 'N/A':
        date_text = f'{date_from}  \u2013  {date_to}'

    prepared_by = (config.get('brand') or {}).get('prepared_by', '')
    right_text = ''
    if prepared_by:
        right_text = f'Prepared by {prepared_by}'
    else:
        right_text = datetime.now().strftime('%B %d, %Y')

    col_w = (PAGE_WIDTH - 2 * MARGIN) / 2
    meta_table = Table(
        [[Paragraph(date_text, meta_style), Paragraph(right_text, meta_style_right)]],
        colWidths=[col_w, col_w],
    )
    meta_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(meta_table)
    story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 2 — Executive Summary
    # ────────────────────────────────────────────────────────────
    if 'executive_summary' in config.get('sections', []) and ai_content.get('summary'):
        toc_entries.append(('Executive Summary', str(toc_page).zfill(2)))
        toc_page += 1
        body_story.append(_SectionHeader('Executive Summary', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        summary = ai_content['summary']
        if summary and summary.full_text.strip():
            # Lead sentence — Fraunces-Medium, 13pt, ink, with a serif drop cap
            lead_style = ParagraphStyle(
                'SummaryLead',
                fontName='Fraunces-Medium',
                fontSize=13,
                textColor=HexColor(INK),
                leading=19,
                spaceAfter=10,
            )
            lead_text = (summary.lead or '').lstrip()
            if lead_text:
                first = lead_text[0]
                rest = lead_text[1:].lstrip()
                styled_lead = f'<font name="Fraunces-SemiBold" size="21">{first}</font>{rest}'
                body_story.append(Paragraph(styled_lead, lead_style))

            # Key stat row — top 3 KPIs by absolute trend magnitude,
            # as a three-column ledger band with hairline dividers
            _kpis_for_strip = [k for k in (kpis or []) if k.get('trend_pct') is not None]
            _kpis_for_strip = sorted(
                _kpis_for_strip,
                key=lambda k: abs(k.get('trend_pct', 0)),
                reverse=True,
            )[:3]

            if _kpis_for_strip:
                stat_cols = []
                for k in _kpis_for_strip:
                    pct = k.get('trend_pct', 0) or 0
                    sign = '+' if pct >= 0 else ''
                    trend_color = brand_color if pct >= 0 else RUST
                    qualifier = _trend_qualifier(k.get('trend_label', ''))
                    trend_text = f"{sign}{pct:.1f}%" + (
                        f" ({qualifier})" if qualifier else ''
                    )
                    stat_cols.append([
                        Paragraph(str(k['name']).upper(), ParagraphStyle(
                            'StatName',
                            fontName='IBMPlexSans-Bold',
                            fontSize=7.5,
                            textColor=HexColor(MUTED),
                            alignment=TA_CENTER,
                            leading=9,
                        )),
                        Paragraph(str(k.get('value', '')), ParagraphStyle(
                            'StatValue',
                            fontName='IBMPlexMono-Bold',
                            fontSize=13,
                            textColor=HexColor(INK),
                            alignment=TA_CENTER,
                            leading=16,
                        )),
                        Paragraph(trend_text, ParagraphStyle(
                            'StatTrend',
                            fontName='IBMPlexSans-Bold',
                            fontSize=9,
                            textColor=HexColor(trend_color),
                            alignment=TA_CENTER,
                            leading=11,
                        )),
                    ])
                col_w = content_width / 3.0
                stat_table = Table(stat_cols, colWidths=[col_w] * 3, hAlign='CENTER')
                stat_table.setStyle(TableStyle([
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('LEFTPADDING', (0, 0), (-1, -1), 8),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                    ('TOPPADDING', (0, 0), (-1, -1), 10),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                    ('LINEABOVE', (0, 0), (-1, 0), 0.75, HexColor(RULE_STRONG)),
                    ('LINEBELOW', (0, -1), (-1, -1), 0.75, HexColor(RULE_STRONG)),
                    ('LINEBEFORE', (1, 0), (1, -1), 0.5, HexColor(RULE)),
                    ('LINEBEFORE', (2, 0), (2, -1), 0.5, HexColor(RULE)),
                ]))
                body_story.append(stat_table)
                body_story.append(Spacer(1, 12))

            # Body prose — context, implication, action in sequence
            body_parts = [summary.context, summary.implication, summary.action]
            body_text = " ".join(p for p in body_parts if p.strip())
            if body_text:
                body_story.append(Paragraph(body_text, body_style))

        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 3 — Key Metrics Overview
    # ────────────────────────────────────────────────────────────
    if 'kpi_overview' in config.get('sections', []):
        toc_entries.append(('Key Metrics Overview', str(toc_page).zfill(2)))
        toc_page += 1
        body_story.append(_SectionHeader('Key Metrics Overview', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        for i, kpi in enumerate(kpis, start=1):
            body_story.append(_KPIRow(kpi, i, content_width, brand_color))
            body_story.append(Spacer(1, 8))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 4 — Charts
    # ────────────────────────────────────────────────────────────
    if 'charts' in config.get('sections', []):
        toc_entries.append(('Charts & Visualizations', str(toc_page).zfill(2)))
        toc_page += 1
        body_story.append(_SectionHeader('Charts & Visualizations', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        rendered_charts = []
        for chart_item in chart_paths:
            if isinstance(chart_item, tuple):
                chart_path = chart_item[0]
                chart_caption = chart_item[2] if len(chart_item) > 2 else None
                chart_label = chart_item[3] if len(chart_item) > 3 else None
            else:
                chart_path = chart_item
                chart_caption = None
                chart_label = None
            if chart_path and os.path.isfile(chart_path):
                rendered_charts.append((chart_path, chart_caption, chart_label))

        chart_h = 200
        chart_gap = 16
        chart_label_style = ParagraphStyle(
            'ChartLabel',
            fontName='IBMPlexMono',
            fontSize=8.5,
            textColor=HexColor(INK),
            alignment=TA_CENTER,
            leading=11,
            spaceBefore=0,
            spaceAfter=2,
        )
        caption_style = ParagraphStyle(
            'ChartCaption',
            fontName='IBMPlexSans',
            fontSize=8.5,
            textColor=HexColor(MUTED),
            alignment=TA_CENTER,
            leading=11,
            spaceBefore=2,
            spaceAfter=2,
        )
        for i in range(0, len(rendered_charts), 2):
            pair = rendered_charts[i:i + 2]
            for j, (chart_path, chart_caption, chart_label) in enumerate(pair):
                try:
                    if chart_label:
                        body_story.append(Paragraph(chart_label.upper(), chart_label_style))
                    chart_img = Image(chart_path, width=content_width, height=chart_h)
                    chart_img.hAlign = 'CENTER'
                    body_story.append(chart_img)
                except Exception:
                    continue
                if chart_caption:
                    body_story.append(Paragraph(chart_caption, caption_style))
                if j < len(pair) - 1:
                    body_story.append(Spacer(1, chart_gap))
            body_story.append(Spacer(1, 10))
            if i + 2 < len(rendered_charts):
                body_story.append(PageBreak())

        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 5 — AI Insight Cards
    # ────────────────────────────────────────────────────────────
    insights = ai_content.get('insights') or []
    ai_skipped = config.get('_ai_skipped', False)
    if 'insights' in config.get('sections', []):
        toc_entries.append(('AI Insights', str(toc_page).zfill(2)))
        toc_page += 1
        body_story.append(_SectionHeader('AI Insights', brand_color, content_width))
        body_story.append(Spacer(1, 10))
        if ai_skipped:
            body_story.append(_AISkippedCard(width=content_width))
            body_story.append(Spacer(1, 10))
        elif insights:
            for i, ins in enumerate(insights[:5], start=1):
                card = _InsightCard(ins, index=i, width=content_width)
                body_story.append(card)
                body_story.append(Spacer(1, 8))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 6 — Anomaly Flags
    # ────────────────────────────────────────────────────────────
    anomalies = ai_content.get('anomalies') or []
    if 'anomalies' in config.get('sections', []) and anomalies:
        toc_entries.append(('Anomaly Flags', str(toc_page).zfill(2)))
        toc_page += 1
        body_story.append(_SectionHeader('Anomaly Flags', brand_color, content_width))
        body_story.append(Spacer(1, 10))
        for anomaly in anomalies[:10]:
            msg = anomaly.get('message', 'Anomaly detected')
            box = _AnomalyBox(msg, width=content_width)
            body_story.append(box)
            body_story.append(Spacer(1, 6))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 7 — Data Table
    # ────────────────────────────────────────────────────────────
    if 'data_table' in config.get('sections', []):
        toc_entries.append(('Data Table', str(toc_page).zfill(2)))
        toc_page += 1
        body_story.append(_SectionHeader('Data Table', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        display_df = df.copy()
        if len(display_df) > 50:
            display_df = display_df.head(50)

        data_table = _build_data_table(display_df, brand_color, content_width)
        body_story.append(data_table)
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 8 — Recommendations
    # ────────────────────────────────────────────────────────────
    show_recommendations = (
        'insights' in config.get('sections', [])
        or 'executive_summary' in config.get('sections', [])
    ) and not ai_skipped
    if show_recommendations:
        toc_entries.append(('Recommendations', str(toc_page).zfill(2)))
        toc_page += 1
        body_story.append(_SectionHeader('Recommendations', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        if ai_skipped:
            body_story.append(_AISkippedCard(width=content_width))
            body_story.append(Spacer(1, 10))
        else:
            recommendations = ai_content.get('recommendations') or []

            if recommendations:
                for idx, rec in enumerate(recommendations, 1):
                    body_story.append(_RecommendationCard(idx, rec, brand_color, content_width))
                    body_story.append(Spacer(1, 8))
            else:
                body_story.append(Paragraph('No recommendations available.', body_style))
        body_story.append(PageBreak())

    # ────────────────────────────────────────────────────────────
    # SECTION 9 — Appendix
    # ────────────────────────────────────────────────────────────
    if 'appendix' in config.get('sections', []):
        toc_entries.append(('Appendix — Raw Data', str(toc_page).zfill(2)))
        toc_page += 1
        body_story.append(_SectionHeader('Appendix — Raw Data', brand_color, content_width))
        body_story.append(Spacer(1, 10))

        appendix_df = df.copy()
        if len(appendix_df) > 100:
            appendix_df = appendix_df.head(100)

        app_table_data = []
        app_header = [str(c).upper() for c in appendix_df.columns]
        app_table_data.append(app_header)
        for _, row in appendix_df.iterrows():
            app_table_data.append([str(v) if pd.notna(v) else '' for v in row])

        app_col_count = len(app_header)
        app_col_width = min(content_width / max(app_col_count, 1), 120)
        app_col_widths = [app_col_width] * app_col_count

        app_table = Table(app_table_data, colWidths=app_col_widths, repeatRows=1)

        app_style_commands = [
            # Plain uppercase mono column labels on PAPER — no colored band.
            ('FONTNAME', (0, 0), (-1, 0), 'IBMPlexMono'),
            ('FONTSIZE', (0, 0), (-1, 0), 8),
            ('TEXTCOLOR', (0, 0), (-1, 0), HexColor(MUTED)),
            ('FONTNAME', (0, 1), (-1, -1), 'IBMPlexMono'),
            ('FONTSIZE', (0, 1), (-1, -1), 7),
            ('GRID', (0, 0), (-1, -1), 0.5, HexColor(GRID_LINE)),
            # Hairline rule beneath the header row, matching the section-header language.
            ('LINEBELOW', (0, 0), (-1, 0), 0.75, HexColor(RULE_STRONG)),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 4),
            ('RIGHTPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ]
        for row_idx in range(1, len(app_table_data)):
            if row_idx % 2 == 0:
                app_style_commands.append(
                    ('BACKGROUND', (0, row_idx), (-1, row_idx), HexColor(ROW_ALT_COLOR))
                )

        app_table.setStyle(TableStyle(app_style_commands))
        body_story.append(app_table)

    # ────────────────────────────────────────────────────────────
    # TOC — built from recorded entries, inserted after cover
    # ────────────────────────────────────────────────────────────
    story.append(_SectionHeader('Table of Contents', brand_color, content_width))
    story.append(Spacer(1, 12))

    toc_rows = []
    for label, pg in toc_entries:
        toc_rows.append([
            Paragraph(label, ParagraphStyle(
                'TOCLabel',
                fontName='IBMPlexSans',
                fontSize=10,
                textColor=HexColor(INK),
                leading=16,
            )),
            Paragraph(pg, ParagraphStyle(
                'TOCPage',
                fontName='IBMPlexMono',
                fontSize=9,
                textColor=HexColor(brand_color),
                alignment=TA_RIGHT,
                leading=16,
            )),
        ])

    col_w = content_width
    toc_table = Table(
        toc_rows,
        colWidths=[col_w * 0.85, col_w * 0.15],
    )
    toc_table.setStyle(TableStyle([
        ('VALIGN',       (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING',  (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING',   (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING',(0, 0), (-1, -1), 5),
        ('LINEBELOW', (0, 0), (-1, -2), 0.4, HexColor(GRID_LINE)),
    ]))
    story.append(toc_table)
    story.append(PageBreak())

    story.extend(body_story)

    doc.build(story, onFirstPage=on_first_page, onLaterPages=on_page)
    logging.info(f"[pdf_service] build_sync completed — report_id={report_id}")

    _strip_standard_fonts(pdf_path)

    if logo_path:
        try:
            os.unlink(logo_path)
        except OSError:
            pass

    return pdf_path
