import io
import logging
import os
import tempfile
from datetime import datetime

import pandas as pd
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.util import Inches, Pt

logger = logging.getLogger(__name__)

SLIDE_W = Inches(13.33)
SLIDE_H = Inches(7.5)
MARGIN = Inches(0.6)
CONTENT_W = SLIDE_W - 2 * MARGIN
TITLE_H = Inches(0.7)

COLOR_INK = RGBColor(0x14, 0x13, 0x1F)
COLOR_WHITE = RGBColor(0xFF, 0xFF, 0xFF)
COLOR_MINT = RGBColor(0x0E, 0x9F, 0x6E)
COLOR_RED = RGBColor(0xEF, 0x44, 0x44)
COLOR_AMBER = RGBColor(0xD9, 0x7A, 0x34)
COLOR_GRAY = RGBColor(0x6B, 0x72, 0x80)

SENTIMENT_COLOR = {
    "positive": COLOR_MINT,
    "negative": COLOR_RED,
    "neutral": COLOR_AMBER,
}

PRIORITY_COLOR = {
    "high": COLOR_RED,
    "medium": COLOR_AMBER,
    "low": COLOR_MINT,
}

TREND_ARROW = {"up": "\u2191", "increasing": "\u2191", "down": "\u2193", "decreasing": "\u2193", "neutral": "\u2192"}


def _hex_to_rgb(hex_color: str) -> RGBColor:
    h = hex_color.lstrip("#")
    if len(h) != 6:
        return COLOR_MINT
    return RGBColor.from_string(h)


def _blank_slide(prs: Presentation):
    layout = prs.slide_layouts[6]
    return prs.slides.add_slide(layout)


def _add_textbox(slide, left, top, width, height, text, font_size=18, bold=False, italic=False, color=COLOR_INK, font_name="IBM Plex Sans", word_wrap=True):
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = word_wrap
    p = tf.paragraphs[0]
    p.text = text
    run = p.runs[0]
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = color
    run.font.name = font_name


def _fill_background(slide, color):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color


def _add_rect(slide, left, top, width, height, fill_color, line_color=None):
    shape = slide.shapes.add_shape(1, left, top, width, height)
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_color
    if line_color:
        shape.line.color.rgb = line_color
    else:
        shape.line.fill.background()


def _slide_title(slide, text, brand_color):
    _add_textbox(slide, MARGIN, MARGIN, CONTENT_W, TITLE_H, text, font_size=28, bold=True, color=COLOR_INK, font_name="Fraunces")
    _add_rect(slide, MARGIN, MARGIN + TITLE_H, CONTENT_W, Inches(0.04), fill_color=brand_color)


def _build_cover(prs, config, user_data, brand_color):
    slide = _blank_slide(prs)
    _fill_background(slide, brand_color)

    logo_url = user_data.get("logo_url")
    if logo_url:
        try:
            import httpx
            resp = httpx.get(logo_url, timeout=5)
            if resp.status_code == 200:
                tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
                tmp.write(resp.content)
                tmp.close()
                slide.shapes.add_picture(tmp.name, MARGIN, MARGIN, width=Inches(1.5))
                os.unlink(tmp.name)
        except Exception as e:
            logger.warning(f"pptx_service: logo fetch failed: {e}")

    company = user_data.get("company_name") or "Report"
    _add_textbox(slide, MARGIN, Inches(2.5), CONTENT_W, Inches(1.0), company, font_size=36, bold=True, color=COLOR_WHITE, font_name="Fraunces")

    title = config.get("title") or "Naxely Report"
    _add_textbox(slide, MARGIN, Inches(3.6), CONTENT_W, Inches(0.8), title, font_size=24, color=COLOR_WHITE)

    date_str = datetime.now().strftime("%B %d, %Y")
    _add_textbox(slide, MARGIN, Inches(4.6), CONTENT_W, Inches(0.5), date_str, font_size=16, color=COLOR_WHITE)

    _add_textbox(slide, SLIDE_W - Inches(3), SLIDE_H - Inches(0.5), Inches(2.4), Inches(0.4), "Generated by Naxely \u00b7 naxely.com", font_size=10, color=COLOR_WHITE)


def _build_executive_summary(prs, summary, brand_color):
    slide = _blank_slide(prs)
    _slide_title(slide, "Executive Summary", brand_color)
    _add_textbox(slide, MARGIN, MARGIN + TITLE_H + Inches(0.2), CONTENT_W, Inches(5.5), summary, font_size=18, color=COLOR_INK, word_wrap=True)


def _build_kpi_slide(prs, kpis, brand_color):
    CARD_W = Inches(5.8)
    CARD_H = Inches(1.6)
    COL_GAP = Inches(0.5)
    ROW_GAP = Inches(0.2)
    ACCENT_W = Inches(0.08)

    for page_start in range(0, len(kpis), 6):
        slide = _blank_slide(prs)
        _slide_title(slide, "Key Performance Indicators", brand_color)

        page_kpis = kpis[page_start:page_start + 6]
        for i, kpi in enumerate(page_kpis):
            col = i % 2
            row = i // 2
            left = MARGIN + col * (CARD_W + COL_GAP)
            top = MARGIN + TITLE_H + Inches(0.3) + row * (CARD_H + ROW_GAP)

            trend = kpi.get("trend", "neutral")
            card_color = COLOR_MINT if trend in ("up", "increasing") else COLOR_RED if trend in ("down", "decreasing") else COLOR_AMBER

            _add_rect(slide, left, top, CARD_W, CARD_H, fill_color=RGBColor(0xF3, 0xF2, 0xF8))
            _add_rect(slide, left, top, ACCENT_W, CARD_H, fill_color=card_color)

            _add_textbox(slide, left + ACCENT_W + Inches(0.15), top + Inches(0.1), CARD_W - ACCENT_W - Inches(0.2), Inches(0.4), kpi.get("name", ""), font_size=13, bold=True, color=COLOR_INK)

            arrow = TREND_ARROW.get(trend, "\u2192")
            value_text = f"{kpi.get('value', '')}  {arrow} {kpi.get('trend_pct', 0):.1f}%"
            _add_textbox(slide, left + ACCENT_W + Inches(0.15), top + Inches(0.55), CARD_W - ACCENT_W - Inches(0.2), Inches(0.6), value_text, font_size=22, bold=True, color=card_color, font_name="IBM Plex Mono")


def _build_chart_slides(prs, chart_paths, brand_color):
    for item in chart_paths:
        if isinstance(item, tuple):
            path, metric = item[0], item[1]
        else:
            path, metric = item, "Chart"

        if not os.path.exists(path):
            logger.warning(f"pptx_service: chart not found, skipping: {path}")
            continue

        slide = _blank_slide(prs)
        _slide_title(slide, metric, brand_color)

        try:
            pic_top = MARGIN + TITLE_H + Inches(0.2)
            pic_h = SLIDE_H - pic_top - MARGIN
            slide.shapes.add_picture(path, MARGIN, pic_top, width=CONTENT_W, height=pic_h)
        except Exception as e:
            logger.warning(f"pptx_service: failed to embed chart {path}: {e}")


def _build_insights_slides(prs, insights, brand_color):
    CARD_W = CONTENT_W
    CARD_H = Inches(1.55)
    ACCENT_W = Inches(0.07)
    GAP = Inches(0.15)

    for page_start in range(0, len(insights), 3):
        slide = _blank_slide(prs)
        _slide_title(slide, "AI Insights", brand_color)

        page_insights = insights[page_start:page_start + 3]
        for i, ins in enumerate(page_insights):
            top = MARGIN + TITLE_H + Inches(0.25) + i * (CARD_H + GAP)
            sentiment = ins.get("sentiment", "neutral")
            accent_color = SENTIMENT_COLOR.get(sentiment, COLOR_AMBER)
            priority = ins.get("priority", "medium").lower()
            priority_color = PRIORITY_COLOR.get(priority, COLOR_AMBER)

            _add_rect(slide, MARGIN, top, CARD_W, CARD_H, fill_color=RGBColor(0xF3, 0xF2, 0xF8))
            _add_rect(slide, MARGIN, top, ACCENT_W, CARD_H, fill_color=accent_color)

            x = MARGIN + ACCENT_W + Inches(0.15)
            w = CARD_W - ACCENT_W - Inches(0.2)

            header = f"{ins.get('kpi', '')}  [{priority.upper()}]"
            _add_textbox(slide, x, top + Inches(0.1), w, Inches(0.35), header, font_size=13, bold=True, color=COLOR_INK)
            _add_textbox(slide, x, top + Inches(0.45), w, Inches(0.5), ins.get("reason", ""), font_size=12, color=COLOR_GRAY)
            _add_textbox(slide, x, top + Inches(0.95), w, Inches(0.45), f"\u2192 {ins.get('action', '')}", font_size=12, color=COLOR_MINT, italic=True)


def _build_anomaly_slide(prs, anomalies, brand_color):
    slide = _blank_slide(prs)
    _slide_title(slide, "Anomaly Flags", brand_color)

    bullet_top = MARGIN + TITLE_H + Inches(0.3)
    for i, anomaly in enumerate(anomalies):
        msg = anomaly.get("message", "")
        _add_textbox(slide, MARGIN + Inches(0.2), bullet_top + i * Inches(0.55), CONTENT_W - Inches(0.2), Inches(0.5), f"\u2022 {msg}", font_size=14, color=COLOR_INK, word_wrap=True)


def _build_footer_slide(prs, brand_color):
    slide = _blank_slide(prs)
    _fill_background(slide, brand_color)
    _add_textbox(slide, MARGIN, Inches(3.2), CONTENT_W, Inches(1.0), "Generated by Naxely", font_size=32, bold=True, color=COLOR_WHITE, font_name="Fraunces")
    _add_textbox(slide, MARGIN, Inches(4.3), CONTENT_W, Inches(0.5), "naxely.com", font_size=18, color=COLOR_WHITE)


def generate_pptx(
    df: pd.DataFrame,
    chart_paths: list,
    ai_content: dict,
    config: dict,
    user_data: dict,
) -> bytes:
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    brand_hex = user_data.get("brand_color") or "#0E9F6E"
    brand_color = _hex_to_rgb(brand_hex)
    ai_skipped = config.get("_ai_skipped", False)
    sections = config.get("sections", [])

    _build_cover(prs, config, user_data, brand_color)

    summary = ai_content.get("summary")
    if summary and not ai_skipped:
        _build_executive_summary(prs, summary, brand_color)
    elif ai_skipped:
        slide = _blank_slide(prs)
        _slide_title(slide, "AI Analysis", brand_color)
        _add_textbox(slide, MARGIN, MARGIN + TITLE_H + Inches(0.3), CONTENT_W, Inches(2.0),
                      "AI analysis was skipped for this report.\nRe-generate with a valid AI provider key to include insights.",
                      font_size=16, color=COLOR_GRAY)

    kpis = config.get("_precomputed_kpis") or []
    if kpis:
        _build_kpi_slide(prs, kpis, brand_color)

    if chart_paths and ("charts" in sections or not sections):
        _build_chart_slides(prs, chart_paths, brand_color)

    insights = ai_content.get("insights") or []
    if insights and not ai_skipped and ("insights" in sections or not sections):
        _build_insights_slides(prs, insights, brand_color)

    anomalies = ai_content.get("anomalies") or []
    if anomalies and ("anomalies" in sections or not sections):
        _build_anomaly_slide(prs, anomalies, brand_color)

    _build_footer_slide(prs, brand_color)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()
